import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "de" | "en";

type Translations = Record<string, Record<Language, string>>;

// Core UI translations
const translations: Translations = {
  // Navigation
  "nav.home": { de: "Home", en: "Home" },
  "nav.progress": { de: "Fortschritt", en: "Progress" },
  "nav.scan": { de: "Scan", en: "Scan" },
  "nav.friends": { de: "Freunde", en: "Friends" },
  "nav.plan": { de: "Plan", en: "Plan" },
  "nav.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "nav.support": { de: "Support", en: "Support" },
  "nav.back": { de: "Zurück", en: "Back" },
  "nav.backToHome": { de: "Zurück zur Startseite", en: "Back to Home" },
  "nav.backToDashboard": { de: "Zurück zum Dashboard", en: "Back to Dashboard" },
  
  // Dashboard
  "dashboard.greeting.morning": { de: "Guten Morgen", en: "Good Morning" },
  "dashboard.greeting.afternoon": { de: "Guten Tag", en: "Good Afternoon" },
  "dashboard.greeting.evening": { de: "Guten Abend", en: "Good Evening" },
  "dashboard.greeting.night": { de: "Gute Nacht", en: "Good Night" },
  "dashboard.score": { de: "Dein Looks Score", en: "Your Looks Score" },
  "dashboard.potential": { de: "Dein Potenzial", en: "Your Potential" },
  "dashboard.streak": { de: "Streak", en: "Streak" },
  "dashboard.level": { de: "Level", en: "Level" },
  "dashboard.scans": { de: "Scans", en: "Scans" },
  "dashboard.quickAccess": { de: "Schnellzugriff", en: "Quick Access" },
  "dashboard.recentAnalyses": { de: "Letzte Analysen", en: "Recent Analyses" },
  "dashboard.all": { de: "Alle", en: "All" },
  "dashboard.startJourney": { de: "Starte deine Reise", en: "Start Your Journey" },
  "dashboard.uploadPhotos": { de: "Lade Fotos hoch und erhalte deine persönliche KI-Analyse", en: "Upload photos and get your personal AI analysis" },
  "dashboard.firstAnalysis": { de: "Erste Analyse starten", en: "Start First Analysis" },
  "dashboard.sinceLastAnalysis": { de: "seit letzter Analyse", en: "since last analysis" },
  "dashboard.progress": { de: "Fortschritt", en: "Progress" },
  "dashboard.reachable": { de: "erreichbar", en: "reachable" },
  "dashboard.personalBest": { de: "Bestwert", en: "Personal Best" },
  "dashboard.yourProgress": { de: "Dein Fortschritt", en: "Your Progress" },
  "dashboard.pointsReachable": { de: "Punkte", en: "Points" },
  "dashboard.outOf": { de: "von", en: "of" },
  "dashboard.share": { de: "Teilen", en: "Share" },
  "dashboard.nextSteps": { de: "Nächste Schritte", en: "Next Steps" },
  "dashboard.revenueAndSubs": { de: "Umsatz & Abos", en: "Revenue & Subs" },
  "dashboard.revenueDesc": { de: "Revenue & Affiliate-Übersicht", en: "Revenue & Affiliate Overview" },
  "dashboard.analyses": { de: "Analysen", en: "Analyses" },
  "dashboard.ranking": { de: "Ranking", en: "Ranking" },
  "dashboard.activeToday": { de: "Heute aktiv werden!", en: "Get active today!" },
  "dashboard.onFire": { de: "🔥 On Fire!", en: "🔥 On Fire!" },
  "dashboard.resultLocked": { de: "Ergebnis gesperrt", en: "Result locked" },
  "dashboard.unlock": { de: "Freischalten", en: "Unlock" },
  "dashboard.progressToPotential": { de: "Fortschritt zu deinem Potenzial", en: "Progress to your potential" },
  "dashboard.pointsPossible": { de: "möglich", en: "possible" },
  "dashboard.viewPlan": { de: "Plan ansehen", en: "View Plan" },
  "dashboard.scoreChart": { de: "Score-Entwicklung", en: "Score Progression" },
  "dashboard.chartLocked": { de: "Chart gesperrt", en: "Chart locked" },
  "dashboard.potential_label": { de: "Potenzial", en: "Potential" },
  "dashboard.premiumFeature": { de: "Premium Feature", en: "Premium Feature" },
  "dashboard.unlockAll": { de: "Schalte alle Features frei", en: "Unlock all features" },
  "dashboard.unlockAllDesc": { de: "Erhalte detaillierte Analysen, deinen personalisierten Plan und Zugang zum AI Coach.", en: "Get detailed analyses, your personalized plan, and access to the AI Coach." },
  "dashboard.goPremium": { de: "Premium werden", en: "Go Premium" },
  "dashboard.noAnalyses": { de: "Noch keine Analysen", en: "No analyses yet" },
  "dashboard.noAnalysesDesc": { de: "Lade ein Foto hoch und erhalte in wenigen Sekunden deinen Looks Score.", en: "Upload a photo and get your Looks Score in seconds." },
  "dashboard.startNewAnalysis": { de: "Neue Analyse starten", en: "Start New Analysis" },
  "dashboard.trackProgress": { de: "Tracke deinen Fortschritt mit regelmäßigen Analysen.", en: "Track your progress with regular analyses." },
  "dashboard.analyzePhoto": { de: "Foto analysieren", en: "Analyze Photo" },
  "dashboard.analysisComplete": { de: "Analyse abgeschlossen", en: "Analysis complete" },
  "dashboard.analyzing": { de: "Wird analysiert...", en: "Analyzing..." },
  "dashboard.validationFailed": { de: "Validierung fehlgeschlagen", en: "Validation failed" },
  "dashboard.failed": { de: "Fehlgeschlagen", en: "Failed" },
  "dashboard.pending": { de: "Ausstehend", en: "Pending" },
  "dashboard.top": { de: "Top", en: "Top" },
  "dashboard.average": { de: "Durchschnitt", en: "Average" },
  "dashboard.potential_badge": { de: "Potenzial", en: "Potential" },
  "dashboard.inProgress": { de: "In Bearbeitung", en: "In Progress" },
  "dashboard.more": { de: "mehr", en: "more" },
  "dashboard.showAll": { de: "anzeigen", en: "show" },
  "dashboard.analysesLocked": { de: "Analysen gesperrt", en: "Analyses locked" },
  "dashboard.noOpenTasks": { de: "Keine offenen Tasks", en: "No open tasks" },
  "dashboard.createPlan": { de: "Plan erstellen", en: "Create Plan" },
  "dashboard.unlockPremium": { de: "Premium freischalten", en: "Unlock Premium" },
  "dashboard.recommendedProducts": { de: "Empfohlene Produkte für dich", en: "Recommended Products for You" },
  "dashboard.achievements": { de: "Achievements", en: "Achievements" },
  "dashboard.achievementsDesc": { de: "Schalte Belohnungen frei und tracke deinen Fortschritt", en: "Unlock rewards and track your progress" },
  
  // Delete Dialog
  "dialog.cancelAnalysis": { de: "Analyse abbrechen?", en: "Cancel analysis?" },
  "dialog.removeAnalysis": { de: "Analyse entfernen?", en: "Remove analysis?" },
  "dialog.cancelAnalysisDesc": { de: "Diese laufende Analyse wird abgebrochen und gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.", en: "This running analysis will be cancelled and deleted. This action cannot be undone." },
  "dialog.removeAnalysisDesc": { de: "Diese fehlgeschlagene Analyse wird aus deiner Historie entfernt. Diese Aktion kann nicht rückgängig gemacht werden.", en: "This failed analysis will be removed from your history. This action cannot be undone." },
  "dialog.cancelBtn": { de: "Abbrechen", en: "Cancel" },
  "dialog.cancelAnalysisBtn": { de: "Analyse abbrechen", en: "Cancel Analysis" },
  "dialog.removeAnalysisBtn": { de: "Analyse entfernen", en: "Remove Analysis" },
  "dialog.analysisCancelled": { de: "Analyse abgebrochen", en: "Analysis cancelled" },
  "dialog.analysisRemoved": { de: "Analyse entfernt", en: "Analysis removed" },
  "dialog.analysisDeleted": { de: "Die Analyse wurde erfolgreich gelöscht.", en: "The analysis was successfully deleted." },
  "dialog.error": { de: "Fehler", en: "Error" },
  "dialog.deleteError": { de: "Die Analyse konnte nicht gelöscht werden.", en: "The analysis could not be deleted." },
  
  // Quick Actions
  "quick.newAnalysis": { de: "Neue Analyse", en: "New Analysis" },
  "quick.newAnalysisDesc": { de: "Lade Fotos hoch für deine KI-Bewertung", en: "Upload photos for your AI rating" },
  "quick.myPlan": { de: "Mein Plan", en: "My Plan" },
  "quick.myPlanDesc": { de: "Dein personalisierter Looksmax-Plan", en: "Your personalized looksmax plan" },
  "quick.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "quick.lifestyleDesc": { de: "Tracke Schlaf, Wasser & Supplements", en: "Track sleep, water & supplements" },
  "quick.friends": { de: "Freunde", en: "Friends" },
  "quick.friendsDesc": { de: "Verbinde dich mit anderen", en: "Connect with others" },
  "quick.progress": { de: "Fortschritt", en: "Progress" },
  "quick.progressDesc": { de: "Verfolge deine Entwicklung", en: "Track your development" },
  "quick.affiliate": { de: "Affiliate", en: "Affiliate" },
  "quick.affiliateDesc": { de: "Verdiene 20% pro Abo", en: "Earn 20% per subscription" },
  "quick.skinType": { de: "Hauttyp erkennen", en: "Detect Skin Type" },
  "quick.skinTypeDesc": { de: "KI-gestützte Hautanalyse", en: "AI-powered skin analysis" },
  
  // Subscription
  "sub.premiumUntil": { de: "Premium bis", en: "Premium until" },
  
  // Analysis
  "analysis.new": { de: "Neue Analyse", en: "New Analysis" },
  "analysis.description": { de: "Lade Fotos hoch für deine KI-Bewertung", en: "Upload photos for your AI rating" },
  
  // Common
  "common.loading": { de: "Wird geladen...", en: "Loading..." },
  "common.save": { de: "Speichern", en: "Save" },
  "common.saving": { de: "Speichern...", en: "Saving..." },
  "common.cancel": { de: "Abbrechen", en: "Cancel" },
  "common.close": { de: "Schließen", en: "Close" },
  "common.delete": { de: "Löschen", en: "Delete" },
  "common.edit": { de: "Bearbeiten", en: "Edit" },
  "common.share": { de: "Teilen", en: "Share" },
  "common.premium": { de: "Premium", en: "Premium" },
  "common.free": { de: "Kostenlos", en: "Free" },
  "common.or": { de: "oder", en: "or" },
  "common.refresh": { de: "Aktualisieren", en: "Refresh" },
  "common.retry": { de: "Erneut versuchen", en: "Try again" },
  "common.error": { de: "Fehler", en: "Error" },
  "common.success": { de: "Erfolg", en: "Success" },
  "common.confirm": { de: "Bestätigen", en: "Confirm" },
  "common.yes": { de: "Ja", en: "Yes" },
  "common.no": { de: "Nein", en: "No" },
  "common.search": { de: "Suchen", en: "Search" },
  "common.send": { de: "Senden", en: "Send" },
  "common.copy": { de: "Kopieren", en: "Copy" },
  "common.copied": { de: "Kopiert!", en: "Copied!" },
  "common.back": { de: "Zurück", en: "Back" },
  "common.dashboard": { de: "Dashboard", en: "Dashboard" },
  "common.tasks": { de: "Aufgaben", en: "Tasks" },
  "common.more": { de: "weitere", en: "more" },
  "common.priority": { de: "Priorität", en: "Priority" },
  
  // Profile
  "profile.edit": { de: "Profil bearbeiten", en: "Edit Profile" },
  "profile.editDesc": { de: "Aktualisiere deinen Namen und dein Profilbild", en: "Update your name and profile picture" },
  "profile.settings": { de: "Design anpassen", en: "Customize Design" },
  "profile.settingsDesc": { de: "Personalisiere das Aussehen der App", en: "Personalize the look of the app" },
  "profile.security": { de: "Sicherheit", en: "Security" },
  "profile.logout": { de: "Ausloggen", en: "Log Out" },
  "profile.user": { de: "Benutzer", en: "User" },
  "profile.admin": { de: "Admin Dashboard", en: "Admin Dashboard" },
  "profile.support": { de: "Support", en: "Support" },
  "profile.firstName": { de: "Vorname", en: "First Name" },
  "profile.firstNamePlaceholder": { de: "Vorname eingeben", en: "Enter first name" },
  "profile.lastName": { de: "Nachname", en: "Last Name" },
  "profile.lastNamePlaceholder": { de: "Nachname eingeben", en: "Enter last name" },
  "profile.displayName": { de: "Anzeigename", en: "Display Name" },
  "profile.displayNamePlaceholder": { de: "Dein Anzeigename", en: "Your display name" },
  "profile.displayNameHint": { de: "Dein Anzeigename kann einmal pro Monat geändert werden.", en: "Your display name can be changed once per month." },
  "profile.displayNameNextChange": { de: "Nächste Änderung möglich in", en: "Next change possible in" },
  "profile.days": { de: "Tagen", en: "days" },
  "profile.day": { de: "Tag", en: "day" },
  "profile.nameAvailable": { de: "Name ist verfügbar", en: "Name is available" },
  "profile.nameTaken": { de: "Dieser Name ist bereits vergeben", en: "This name is already taken" },
  "profile.changeImage": { de: "Bild ändern", en: "Change Image" },
  "profile.uploading": { de: "Wird hochgeladen...", en: "Uploading..." },
  "profile.email": { de: "E-Mail", en: "Email" },
  "profile.userId": { de: "Deine User-ID", en: "Your User ID" },
  "profile.userIdHint": { de: "Für Support-Anfragen oder zur Identifikation", en: "For support requests or identification" },
  "profile.userIdCopied": { de: "User-ID kopiert!", en: "User ID copied!" },
  "profile.subStatus": { de: "Abo-Status", en: "Subscription Status" },
  "profile.active": { de: "Aktiv", en: "Active" },
  "profile.expiresSoon": { de: "Läuft bald ab", en: "Expires soon" },
  "profile.expiresIn": { de: "Dein Abo läuft in", en: "Your subscription expires in" },
  "profile.expiresInDays": { de: "Tagen ab!", en: "days!" },
  "profile.renewsAt": { de: "Verlängert am:", en: "Renews on:" },
  "profile.unlimitedDuration": { de: "Unbegrenzte Laufzeit", en: "Unlimited duration" },
  "profile.upgradeHint": { de: "Upgrade für alle Premium-Features", en: "Upgrade for all premium features" },
  "profile.redeemCode": { de: "Promocode einlösen", en: "Redeem Promo Code" },
  "profile.manageSub": { de: "Abo verwalten", en: "Manage Subscription" },
  "profile.refund": { de: "Widerrufsrecht", en: "Right of Withdrawal" },
  "profile.viewRequests": { de: "Anträge ansehen", en: "View Requests" },
  "profile.adminGranted": { de: "Von Admin vergeben", en: "Granted by Admin" },
  "profile.deleteAccount": { de: "Konto löschen", en: "Delete Account" },
  "profile.deleteAccountTitle": { de: "Konto löschen anfordern", en: "Request Account Deletion" },
  "profile.deleteAccountDesc1": { de: "Wir senden dir eine Bestätigungs-E-Mail an", en: "We'll send a confirmation email to" },
  "profile.deleteAccountDesc2": { de: "Klicke auf den Link in der E-Mail und gib dein Passwort ein, um die Löschung endgültig zu bestätigen.", en: "Click the link in the email and enter your password to confirm the deletion." },
  "profile.deleteAccountSubHint": { de: "Hinweis: Dein aktives Abo wird separat über Stripe gekündigt.", en: "Note: Your active subscription will be cancelled separately via Stripe." },
  "profile.sendConfirmEmail": { de: "Bestätigungs-E-Mail senden", en: "Send Confirmation Email" },
  "profile.sendingEmail": { de: "Wird gesendet...", en: "Sending..." },
  "profile.mode": { de: "Modus", en: "Mode" },
  "profile.dark": { de: "Dunkel", en: "Dark" },
  "profile.light": { de: "Hell", en: "Light" },
  "profile.accentColor": { de: "Akzentfarbe", en: "Accent Color" },
  "profile.background": { de: "Hintergrund", en: "Background" },
  
  // Notifications
  "notifications.title": { de: "Benachrichtigungen", en: "Notifications" },
  "notifications.empty": { de: "Keine neuen Benachrichtigungen", en: "No new notifications" },
  "notifications.unreadMessages": { de: "Ungelesene Nachrichten", en: "Unread Messages" },
  "notifications.friendRequests": { de: "Freundschaftsanfragen", en: "Friend Requests" },
  "notifications.partnerRequests": { de: "Partner-Anfragen", en: "Partner Requests" },

  // Motivation
  "motivation.readyForProgress": { de: "Bereit für einen weiteren Tag voller Fortschritt? 💪", en: "Ready for another day of progress? 💪" },
  
  // Language
  "language.de": { de: "Deutsch", en: "German" },
  "language.en": { de: "Englisch", en: "English" },

  // Skin Type Analyzer
  "skin.detect": { de: "Hauttyp erkennen", en: "Detect Skin Type" },
  "skin.title": { de: "AI Hauttyp-Erkennung", en: "AI Skin Type Detection" },
  "skin.description": { de: "Lade ein Nahaufnahme-Foto deines Gesichts hoch für eine KI-gestützte Hauttyp-Analyse.", en: "Upload a close-up photo of your face for an AI-powered skin type analysis." },
  "skin.upload": { de: "Tippe hier, um ein Foto hochzuladen", en: "Tap here to upload a photo" },
  "skin.uploadTip": { de: "Am besten: Nahaufnahme, gutes Licht, kein Make-up", en: "Best: close-up, good lighting, no makeup" },
  "skin.analyzing": { de: "Hauttyp wird analysiert...", en: "Analyzing skin type..." },
  "skin.confidence": { de: "Sicherheit", en: "Confidence" },
  "skin.characteristics": { de: "Merkmale", en: "Characteristics" },
  "skin.recommendations": { de: "Empfohlene Produkte", en: "Recommended Products" },
  "skin.tips": { de: "Tipps", en: "Tips" },
  "skin.retry": { de: "Neue Analyse", en: "New Analysis" },
  "skin.error": { de: "Analyse fehlgeschlagen", en: "Analysis failed" },

  // Login Page
  "login.welcome": { de: "Willkommen zurück", en: "Welcome back" },
  "login.subtitle": { de: "Melde dich an, um fortzufahren", en: "Sign in to continue" },
  "login.subtitleDesktop": { de: "Melde dich an, um deinen Fortschritt zu tracken.", en: "Sign in to track your progress." },
  "login.email": { de: "E-Mail", en: "Email" },
  "login.password": { de: "Passwort", en: "Password" },
  "login.forgot": { de: "Vergessen?", en: "Forgot?" },
  "login.submit": { de: "Anmelden", en: "Sign In" },
  "login.submitting": { de: "Anmelden...", en: "Signing in..." },
  "login.googleLogin": { de: "Mit Google anmelden", en: "Sign in with Google" },
  "login.googleConnecting": { de: "Verbinde...", en: "Connecting..." },
  "login.googleConnectingFull": { de: "Verbinde mit Google...", en: "Connecting with Google..." },
  "login.noAccount": { de: "Noch kein Konto?", en: "Don't have an account?" },
  "login.register": { de: "Jetzt registrieren", en: "Register now" },
  "login.accountLocked": { de: "Konto gesperrt", en: "Account locked" },
  "login.tooManyAttempts": { de: "Zu viele Fehlversuche", en: "Too many failed attempts" },
  "login.accountLockedDesc": { de: "Dein Konto ist vorübergehend gesperrt. Bitte warte", en: "Your account is temporarily locked. Please wait" },
  "login.attemptsRemaining": { de: "Versuche verbleibend", en: "attempts remaining" },
  "login.attemptsBeforeLock": { de: "bevor dein Konto für 5 Minuten gesperrt wird.", en: "before your account is locked for 5 minutes." },
  "login.forgotPasswordReset": { de: "Passwort vergessen? Jetzt zurücksetzen", en: "Forgot password? Reset now" },
  "login.failed": { de: "Anmeldung fehlgeschlagen", en: "Login failed" },
  "login.wrongCredentials": { de: "E-Mail oder Passwort ist falsch. Wenn du dein Passwort vergessen hast, nutze 'Vergessen?'.", en: "Email or password is incorrect. If you forgot your password, use 'Forgot?'." },
  "login.emailNotConfirmed": { de: "E-Mail nicht bestätigt", en: "Email not confirmed" },
  "login.emailNotConfirmedDesc": { de: "Bitte bestätige zuerst deine E-Mail-Adresse. Überprüfe deinen Posteingang.", en: "Please confirm your email address first. Check your inbox." },
  "login.tooManyRequests": { de: "Zu viele Anfragen", en: "Too many requests" },
  "login.tooManyRequestsDesc": { de: "Bitte warte 1-2 Minuten und versuche es dann erneut.", en: "Please wait 1-2 minutes and try again." },
  "login.welcomeBack": { de: "Willkommen zurück!", en: "Welcome back!" },
  "login.redirecting": { de: "Du wirst zum Dashboard weitergeleitet.", en: "You are being redirected to the dashboard." },
  "login.potentialWaiting": { de: "Dein Potenzial wartet", en: "Your potential awaits" },
  "login.trackProgressGoal": { de: "Tracke deinen Fortschritt und erreiche deinen Ziel-Score.", en: "Track your progress and reach your goal score." },
  "login.lockedFor": { de: "Konto für", en: "Account locked for" },
  "login.locked": { de: "gesperrt.", en: "locked." },
  "login.googleFailed": { de: "Google-Anmeldung fehlgeschlagen", en: "Google sign-in failed" },
  "login.pleaseWait": { de: "Bitte warten", en: "Please wait" },
  "login.waitAndRetry": { de: "Bitte warte und versuche es dann erneut.", en: "Please wait and try again." },

  // Register Page
  "register.title": { de: "Konto erstellen", en: "Create Account" },
  "register.subtitle": { de: "Starte kostenlos – keine Kreditkarte nötig", en: "Start for free – no credit card required" },
  "register.subtitleDesktop": { de: "Starte kostenlos – keine Kreditkarte erforderlich.", en: "Start for free – no credit card required." },
  "register.firstName": { de: "Vorname", en: "First Name" },
  "register.lastName": { de: "Nachname", en: "Last Name" },
  "register.displayName": { de: "Anzeigename", en: "Display Name" },
  "register.displayNamePlaceholder": { de: "Dein Anzeigename", en: "Your display name" },
  "register.displayNameHint": { de: "Dieser Name wird öffentlich angezeigt. Du kannst ihn später ändern.", en: "This name is shown publicly. You can change it later." },
  "register.email": { de: "E-Mail", en: "Email" },
  "register.password": { de: "Passwort", en: "Password" },
  "register.passwordMin": { de: "Mind. 8 Zeichen", en: "Min. 8 characters" },
  "register.confirmPassword": { de: "Passwort bestätigen", en: "Confirm Password" },
  "register.confirmPasswordPlaceholder": { de: "Passwort wiederholen", en: "Repeat password" },
  "register.passwordMismatch": { de: "Passwörter stimmen nicht überein", en: "Passwords don't match" },
  "register.referralCode": { de: "Freundescode (optional)", en: "Referral Code (optional)" },
  "register.referralCodeHint": { de: "Hast du einen Code von einem Freund erhalten?", en: "Did you receive a code from a friend?" },
  "register.referralCodeHintDesktop": { de: "Hast du einen Code von einem Freund erhalten? Gib ihn hier ein!", en: "Did you receive a code from a friend? Enter it here!" },
  "register.submit": { de: "Registrieren", en: "Register" },
  "register.submitDesktop": { de: "Kostenlos registrieren", en: "Register for free" },
  "register.submitting": { de: "Registrieren...", en: "Registering..." },
  "register.submittingDesktop": { de: "Wird erstellt...", en: "Creating..." },
  "register.googleRegister": { de: "Mit Google registrieren", en: "Sign up with Google" },
  "register.connecting": { de: "Verbinde...", en: "Connecting..." },
  "register.hasAccount": { de: "Bereits registriert?", en: "Already registered?" },
  "register.loginNow": { de: "Jetzt anmelden", en: "Sign in now" },
  "register.termsPrefix": { de: "Mit der Registrierung akzeptierst du unsere", en: "By registering you accept our" },
  "register.termsLink": { de: "AGB", en: "Terms" },
  "register.termsAnd": { de: "und", en: "and" },
  "register.privacyLink": { de: "Datenschutz", en: "Privacy Policy" },
  "register.nameHint": { de: "Dein echter Name wird privat gespeichert und ist nur für dich sichtbar.", en: "Your real name is stored privately and is only visible to you." },
  "register.onlyLetters": { de: "Nur Buchstaben erlaubt (keine Zahlen oder Sonderzeichen)", en: "Only letters allowed (no numbers or special characters)" },
  "register.startTransformation": { de: "Starte deine", en: "Start your" },
  "register.transformation": { de: "Transformation", en: "Transformation" },
  "register.invalidName": { de: "Ungültiger Name", en: "Invalid name" },
  "register.invalidNameDesc": { de: "Vor- und Nachname dürfen nur Buchstaben enthalten.", en: "First and last name may only contain letters." },
  "register.missingFields": { de: "Fehlende Angaben", en: "Missing information" },
  "register.missingFieldsDesc": { de: "Bitte gib deinen Vor- und Nachnamen ein.", en: "Please enter your first and last name." },
  "register.invalidDisplayName": { de: "Ungültiger Anzeigename", en: "Invalid display name" },
  "register.nameUnavailable": { de: "Name nicht verfügbar", en: "Name unavailable" },
  "register.nameUnavailableDesc": { de: "Dieser Anzeigename ist bereits vergeben. Bitte wähle einen anderen.", en: "This display name is already taken. Please choose another." },
  "register.emailExists": { de: "E-Mail bereits registriert", en: "Email already registered" },
  "register.emailExistsDesc": { de: "Diese E-Mail existiert bereits. Falls du noch keine Bestätigung hast, sende die Bestätigungs-Mail erneut.", en: "This email already exists. If you haven't confirmed yet, resend the confirmation email." },
  "register.accountCreated": { de: "Konto erstellt!", en: "Account created!" },
  "register.canLogin": { de: "Du kannst dich jetzt anmelden.", en: "You can now sign in." },
  "register.failedTitle": { de: "Registrierung fehlgeschlagen", en: "Registration failed" },
  "register.rateLimitTitle": { de: "Zu viele Anfragen", en: "Too many requests" },
  "register.rateLimitDesc": { de: "Das E-Mail-Limit wurde erreicht. Bitte warte ca. 1 Stunde oder verwende eine andere E-Mail-Adresse.", en: "The email limit has been reached. Please wait about 1 hour or use a different email address." },
  "register.weakPassword": { de: "Unsicheres Passwort", en: "Weak password" },
  "register.weakPasswordDesc": { de: "Dieses Passwort wurde in Datenlecks gefunden und ist nicht sicher. Bitte wähle ein anderes, einzigartiges Passwort.", en: "This password was found in data breaches and is not secure. Please choose a different, unique password." },
  "register.googleFailed": { de: "Google-Registrierung fehlgeschlagen", en: "Google registration failed" },
  "register.passwordStrength.veryWeak": { de: "Sehr schwach", en: "Very weak" },
  "register.passwordStrength.weak": { de: "Schwach", en: "Weak" },
  "register.passwordStrength.medium": { de: "Mittel", en: "Medium" },
  "register.passwordStrength.strong": { de: "Stark", en: "Strong" },
  "register.passwordStrength.veryStrong": { de: "Sehr stark", en: "Very strong" },
  "register.passwordStrength.label": { de: "Passwortstärke:", en: "Password strength:" },
  "register.passwordReq.min8": { de: "Mindestens 8 Zeichen", en: "At least 8 characters" },
  "register.passwordReq.cases": { de: "Groß- und Kleinbuchstaben", en: "Upper and lowercase letters" },
  "register.passwordReq.number": { de: "Mindestens eine Zahl", en: "At least one number" },
  "register.passwordReq.special": { de: "Sonderzeichen (z.B. !@#$)", en: "Special character (e.g. !@#$)" },
  "register.passwordReq.breach": { de: "Passwörter aus Datenlecks werden abgelehnt", en: "Passwords from data breaches will be rejected" },
  "register.benefit1": { de: "KI-Analyse deines Aussehens", en: "AI analysis of your appearance" },
  "register.benefit2": { de: "Personalisierter Looksmax-Plan", en: "Personalized looksmax plan" },
  "register.benefit3": { de: "Progress Tracking mit Streak-System", en: "Progress tracking with streak system" },
  "register.benefit4": { de: "Zugang zum AI Coach", en: "Access to AI Coach" },

  // Forgot Password
  "forgot.title": { de: "Passwort vergessen", en: "Forgot Password" },
  "forgot.subtitle": { de: "Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen.", en: "Enter your email address and we'll send you a reset link." },
  "forgot.email": { de: "E-Mail-Adresse", en: "Email address" },
  "forgot.submit": { de: "Link senden", en: "Send link" },
  "forgot.submitting": { de: "Wird gesendet...", en: "Sending..." },
  "forgot.sent": { de: "E-Mail gesendet!", en: "Email sent!" },
  "forgot.sentDesc": { de: "Wenn ein Konto mit dieser E-Mail existiert, erhältst du einen Reset-Link.", en: "If an account with this email exists, you'll receive a reset link." },
  "forgot.checkInbox": { de: "Überprüfe deinen Posteingang", en: "Check your inbox" },
  "forgot.backToLogin": { de: "Zurück zum Login", en: "Back to login" },
  "forgot.waitCooldown": { de: "Bitte warten", en: "Please wait" },
  "forgot.waitCooldownDesc": { de: "Du kannst in {seconds} Sekunden erneut eine E-Mail anfordern.", en: "You can request another email in {seconds} seconds." },
  "forgot.tooManyRequests": { de: "Zu viele Anfragen. Bitte warte einen Moment und versuche es erneut.", en: "Too many requests. Please wait a moment and try again." },
  "forgot.error": { de: "E-Mail konnte nicht gesendet werden. Bitte versuche es erneut.", en: "Email could not be sent. Please try again." },
  "forgot.resend": { de: "Erneut senden", en: "Resend" },
  "forgot.resendIn": { de: "Erneut senden in", en: "Resend in" },

  // Progress Page
  "progress.title": { de: "Dein Fortschritt", en: "Your Progress" },
  "progress.subtitle": { de: "Verfolge deine Entwicklung über Zeit", en: "Track your development over time" },
  "progress.analyses": { de: "Analysen", en: "Analyses" },
  "progress.loading": { de: "Lade Analysen...", en: "Loading analyses..." },
  "progress.noAnalyses": { de: "Keine Analysen vorhanden", en: "No analyses available" },
  "progress.noAnalysesDesc": { de: "Starte deine erste Analyse, um deinen Fortschritt zu tracken.", en: "Start your first analysis to track your progress." },
  "progress.firstAnalysis": { de: "Erste Analyse starten", en: "Start first analysis" },
  "progress.current": { de: "Aktuell", en: "Current" },
  "progress.potential": { de: "Potenzial", en: "Potential" },
  "progress.possible": { de: "möglich", en: "possible" },
  "progress.avgScore": { de: "Durchschnitt", en: "Average" },
  "progress.highest": { de: "Höchster", en: "Highest" },
  "progress.total": { de: "Gesamt", en: "Total" },
  "progress.scoreChart": { de: "Score-Entwicklung", en: "Score Progression" },
  "progress.totalAnalyses": { de: "Analysen total", en: "total analyses" },
  "progress.score": { de: "Score", en: "Score" },
  "progress.premiumTitle": { de: "Premium Feature", en: "Premium Feature" },
  "progress.premiumDesc": { de: "Verfolge deinen Fortschritt mit Vorher/Nachher-Vergleichen und detaillierten Statistiken.", en: "Track your progress with before/after comparisons and detailed statistics." },
  "progress.premiumFeature1": { de: "Vorher/Nachher Fotovergleich", en: "Before/After photo comparison" },
  "progress.premiumFeature2": { de: "Score-Entwicklung über Zeit", en: "Score progression over time" },
  "progress.premiumFeature3": { de: "Detaillierte Statistiken", en: "Detailed statistics" },
  "progress.premiumFeature4": { de: "Stärken & Schwächen Trends", en: "Strengths & Weaknesses Trends" },
  "progress.goPremium": { de: "Jetzt Premium werden", en: "Go Premium now" },
  "progress.beforeAfter": { de: "Vorher / Nachher", en: "Before / After" },
  "progress.before": { de: "Vorher", en: "Before" },
  "progress.after": { de: "Nachher", en: "After" },
  "progress.compareTitle": { de: "Vergleich", en: "Comparison" },
  "progress.skinQuality": { de: "Hautqualität", en: "Skin Quality" },
  "progress.hairStyling": { de: "Haare & Styling", en: "Hair & Styling" },
  "progress.jawlineBody": { de: "Jawline & Body", en: "Jawline & Body" },
  "progress.eyeArea": { de: "Augenbereich", en: "Eye Area" },
  "progress.couldNotLoad": { de: "Analysen konnten nicht geladen werden.", en: "Analyses could not be loaded." },
  "progress.detailedAnalysis": { de: "Detaillierte Analyse", en: "Detailed Analysis" },
  "progress.byCategory": { de: "Bewertung nach Kategorie", en: "Rating by category" },
  "progress.viewFull": { de: "Vollständig ansehen", en: "View full" },
  
  // Plan Page
  "plan.title": { de: "Dein Looksmax-Plan", en: "Your Looksmax Plan" },
  "plan.headerTitle": { de: "Looksmax Plan", en: "Looksmax Plan" },
  "plan.subtitle": { de: "Personalisiert basierend auf deiner Analyse", en: "Personalized based on your analysis" },
  "plan.subtitleScore": { de: "Score:", en: "Score:" },
  "plan.subtitleNoAnalysis": { de: "Starte eine Analyse für einen personalisierten Plan.", en: "Start an analysis for a personalized plan." },
  "plan.noAnalysis": { de: "Keine Analyse vorhanden", en: "No analysis available" },
  "plan.noAnalysisDesc": { de: "Mache zuerst eine Analyse, damit wir deinen Plan personalisieren können.", en: "Do an analysis first so we can personalize your plan." },
  "plan.generate": { de: "Plan erstellen", en: "Generate Plan" },
  "plan.generating": { de: "Plan wird erstellt...", en: "Generating plan..." },
  "plan.generatingAI": { de: "KI erstellt Plan...", en: "AI generating plan..." },
  "plan.generated": { de: "Plan erstellt! 🎯", en: "Plan created! 🎯" },
  "plan.generatedDesc": { de: "Dein personalisierter Looksmax-Plan basiert auf deiner Analyse.", en: "Your personalized looksmax plan is based on your analysis." },
  "plan.yourSubScores": { de: "Deine Teil-Scores", en: "Your Sub-Scores" },
  "plan.premiumDesc": { de: "Der personalisierte Looksmax-Plan ist nur für Premium-Mitglieder verfügbar. Erhalte deinen maßgeschneiderten Verbesserungsplan.", en: "The personalized looksmax plan is only available for premium members. Get your tailored improvement plan." },
  "plan.goPremium": { de: "Premium werden", en: "Go Premium" },
  "plan.focusAreas": { de: "Fokus-Bereiche", en: "Focus Areas" },
  "plan.topPriorities": { de: "Deine Top-Prioritäten", en: "Your Top Priorities" },
  "plan.skincare": { de: "Skincare", en: "Skincare" },
  "plan.hairBeard": { de: "Haare & Bart", en: "Hair & Beard" },
  "plan.bodyGym": { de: "Körper & Gym", en: "Body & Gym" },
  "plan.styleClothing": { de: "Style & Kleidung", en: "Style & Clothing" },
  "plan.teethSmile": { de: "Zähne & Lächeln", en: "Teeth & Smile" },
  "plan.mindsetPosture": { de: "Mindset & Haltung", en: "Mindset & Posture" },
  "plan.symmetry": { de: "Symmetrie", en: "Symmetry" },
  "plan.jawline": { de: "Jawline", en: "Jawline" },
  "plan.eyes": { de: "Augen", en: "Eyes" },
  "plan.skin": { de: "Haut", en: "Skin" },
  "plan.hair": { de: "Haare", en: "Hair" },
  "plan.charisma": { de: "Ausstrahlung", en: "Charisma" },
  "plan.overallProgress": { de: "Gesamtfortschritt", en: "Overall Progress" },
  "plan.tasks": { de: "Aufgaben", en: "Tasks" },
  "plan.completed": { de: "erledigt", en: "completed" },
  "plan.allDone": { de: "🎉 Alles erledigt! Großartige Arbeit.", en: "🎉 All done! Great work." },
  "plan.almostDone": { de: "💪 Fast geschafft! Bleib dran.", en: "💪 Almost there! Keep going." },
  "plan.goodProgress": { de: "👍 Gute Fortschritte! Weiter so.", en: "👍 Good progress! Keep it up." },
  "plan.goodStart": { de: "🚀 Guter Start! Jeden Tag ein bisschen besser.", en: "🚀 Good start! A little better every day." },
  "plan.startPlan": { de: "📋 Beginne mit deinem Plan!", en: "📋 Start your plan!" },
  "plan.doAnalysisFirst": { de: "Zuerst Analyse durchführen", en: "Do analysis first" },
  "plan.doAnalysisFirstDesc": { de: "Für einen personalisierten Plan brauchen wir deine Analyse-Ergebnisse.", en: "We need your analysis results for a personalized plan." },
  "plan.startAnalysis": { de: "Analyse starten", en: "Start Analysis" },
  "plan.planReady": { de: "Personalisierter Plan bereit", en: "Personalized plan ready" },
  "plan.planReadyDesc": { de: "Basierend auf deiner Analyse erstellen wir einen Plan, der genau auf deine Schwächen abzielt.", en: "Based on your analysis, we'll create a plan targeting your weaknesses." },
  "plan.generatePlan": { de: "Plan generieren", en: "Generate Plan" },
  "plan.yourPlan": { de: "Dein persönlicher Plan", en: "Your Personal Plan" },
  "plan.basedOnAnalysis": { de: "Basierend auf deiner Analyse", en: "Based on your analysis" },
  "plan.ofCompleted": { de: "von", en: "of" },
  "plan.regenerate": { de: "Plan neu generieren", en: "Regenerate Plan" },
  "plan.basedOnCurrentAnalysis": { de: "Basierend auf deiner aktuellen Analyse", en: "Based on your current analysis" },

  // Coach Page
  "coach.title": { de: "AI Coach", en: "AI Coach" },
  "coach.greeting": { de: "Frag mich, was du verbessern kannst.", en: "Ask me what you can improve." },
  "coach.placeholder": { de: "Schreib eine Nachricht...", en: "Write a message..." },
  "coach.premiumTitle": { de: "Premium Feature", en: "Premium Feature" },
  "coach.premiumDesc": { de: "Der AI Coach hilft dir mit personalisierten Tipps und Empfehlungen.", en: "The AI Coach helps you with personalized tips and recommendations." },
  "coach.newChat": { de: "Neues Gespräch", en: "New Conversation" },
  "coach.deleted": { de: "Gespräch gelöscht", en: "Conversation deleted" },
  "coach.allDeleted": { de: "Alle Gespräche gelöscht", en: "All conversations deleted" },
  "coach.archived": { de: "Gespräch archiviert", en: "Conversation archived" },
  "coach.unarchived": { de: "Gespräch wiederhergestellt", en: "Conversation restored" },
  "coach.renamed": { de: "Gespräch umbenannt", en: "Conversation renamed" },
  "coach.micBlocked": { de: "Mikrofon blockiert", en: "Microphone blocked" },
  "coach.micBlockedDesc": { de: "Bitte erlaube den Zugriff auf dein Mikrofon.", en: "Please allow microphone access." },
  "coach.noSpeech": { de: "Keine Sprache erkannt", en: "No speech detected" },
  "coach.noSpeechDesc": { de: "Bitte sprich lauter / näher ans Mikrofon und versuche es erneut.", en: "Please speak louder / closer to the microphone and try again." },
  "coach.micUnavailable": { de: "Mikrofon nicht verfügbar", en: "Microphone unavailable" },
  "coach.suggestion1": { de: "Was sollte ich zuerst verbessern?", en: "What should I improve first?" },
  "coach.suggestion2": { de: "Skincare Routine für Anfänger", en: "Skincare routine for beginners" },
  "coach.suggestion3": { de: "Wie verbessere ich meine Jawline?", en: "How do I improve my jawline?" },

  // Support Page
  "support.title": { de: "Support", en: "Support" },
  "support.newTicket": { de: "Neues Ticket", en: "New Ticket" },
  "support.myTickets": { de: "Meine Tickets", en: "My Tickets" },
  "support.subject": { de: "Betreff", en: "Subject" },
  "support.message": { de: "Nachricht", en: "Message" },
  "support.category": { de: "Kategorie", en: "Category" },
  "support.priority": { de: "Priorität", en: "Priority" },
  "support.technical": { de: "Technisches Problem", en: "Technical Issue" },
  "support.billing": { de: "Zahlung & Abrechnung", en: "Billing & Payments" },
  "support.account": { de: "Konto & Profil", en: "Account & Profile" },
  "support.other": { de: "Sonstiges", en: "Other" },
  "support.open": { de: "Offen", en: "Open" },
  "support.inProgress": { de: "In Bearbeitung", en: "In Progress" },
  "support.resolved": { de: "Gelöst", en: "Resolved" },
  "support.closed": { de: "Geschlossen", en: "Closed" },
  "support.noTickets": { de: "Noch keine Tickets", en: "No tickets yet" },
  "support.noTicketsDesc": { de: "Erstelle ein Ticket, wenn du Hilfe brauchst.", en: "Create a ticket when you need help." },
  "support.sendMessage": { de: "Nachricht senden", en: "Send message" },
  "support.noMessages": { de: "Noch keine Nachrichten", en: "No messages yet" },
  "support.supportTeam": { de: "Support-Team", en: "Support Team" },
  "support.you": { de: "Du", en: "You" },

  // Upload Page
  "upload.title": { de: "KI-Analyse", en: "AI Analysis" },
  "upload.subtitle": { de: "Lade deine Fotos hoch", en: "Upload your photos" },
  "upload.front": { de: "Frontal", en: "Front" },
  "upload.frontDesc": { de: "Gesicht von vorne", en: "Face from the front" },
  "upload.side": { de: "Seite", en: "Side" },
  "upload.sideDesc": { de: "Profil-Ansicht", en: "Profile view" },
  "upload.body": { de: "Körper", en: "Body" },
  "upload.bodyDesc": { de: "Ganzkörper (optional)", en: "Full body (optional)" },
  "upload.analyze": { de: "Analyse starten", en: "Start Analysis" },
  "upload.analyzing": { de: "Wird analysiert...", en: "Analyzing..." },
  "upload.guidelines": { de: "Foto-Richtlinien", en: "Photo Guidelines" },
  "upload.dailyLimit": { de: "Tägliches Limit erreicht", en: "Daily limit reached" },
  "upload.dropHere": { de: "Fotos hier ablegen", en: "Drop photos here" },
  "upload.invalidFormat": { de: "Ungültiges Format", en: "Invalid format" },
  "upload.invalidFormatDesc": { de: "Bitte lade nur Bilder hoch (JPG, PNG, WebP)", en: "Please upload images only (JPG, PNG, WebP)" },
  "upload.replacePhoto": { de: "Foto ersetzen", en: "Replace photo" },
  "upload.photoReplaced": { de: "wird ersetzt", en: "will be replaced" },
  "upload.frontRequired": { de: "Frontalfoto erforderlich", en: "Front photo required" },
  "upload.frontRequiredDesc": { de: "Bitte lade mindestens ein Frontalfoto hoch", en: "Please upload at least a front photo" },
  "upload.uploadSuccess": { de: "Upload erfolgreich!", en: "Upload successful!" },
  "upload.processingAnalysis": { de: "Deine Analyse wird jetzt verarbeitet...", en: "Your analysis is now being processed..." },
  "upload.uploadFailed": { de: "Upload fehlgeschlagen", en: "Upload failed" },
  "upload.tryAgain": { de: "Bitte versuche es erneut", en: "Please try again" },
  "upload.freeAnalysisInfo": { de: "Du erhältst deinen Looks Score (ohne Details).", en: "You'll get your Looks Score (without details)." },
  "upload.freeAnalysis": { de: "Kostenlose Analyse:", en: "Free Analysis:" },
  "upload.yourPhotos": { de: "Deine Fotos", en: "Your photos" },
  "upload.tapToRemove": { de: "Tippe auf X zum Entfernen", en: "Tap X to remove" },
  "upload.photoUpload": { de: "Foto hochladen", en: "Upload photo" },
  "upload.dragDrop": { de: "Drag & Drop oder klicke zum Auswählen", en: "Drag & drop or click to select" },
  "upload.maxSize": { de: "JPG, PNG oder WebP • Max. 5MB", en: "JPG, PNG or WebP • Max 5MB" },
  "upload.tipsTitle": { de: "Tipps für bessere Ergebnisse", en: "Tips for better results" },
  "upload.allGuidelines": { de: "Alle Richtlinien", en: "All guidelines" },
  "upload.tip1": { de: "Gute Beleuchtung (Tageslicht ist ideal)", en: "Good lighting (daylight is ideal)" },
  "upload.tip2": { de: "Neutraler Gesichtsausdruck", en: "Neutral facial expression" },
  "upload.tip3": { de: "Haare aus dem Gesicht", en: "Hair away from face" },
  "upload.tip4": { de: "Keine Filter oder Bearbeitung", en: "No filters or editing" },
  "upload.uploading": { de: "Wird hochgeladen...", en: "Uploading..." },
  "upload.securePhotos": { de: "Deine Fotos werden sicher gespeichert und nur für die Analyse verwendet", en: "Your photos are stored securely and used only for analysis" },
  "upload.dailyLimitTitle": { de: "Tageslimit erreicht", en: "Daily limit reached" },
  "upload.dailyLimitDesc": { de: "Du hast heute bereits", en: "You have already used" },
  "upload.dailyLimitDesc2": { de: "von", en: "of" },
  "upload.dailyLimitDesc3": { de: "Analysen verwendet. Morgen kannst du wieder analysieren!", en: "analyses today. You can analyze again tomorrow!" },
  "upload.lifetimeUpgrade": { de: "Lifetime Upgrade", en: "Lifetime Upgrade" },
  "upload.lifetimeDesc": { de: "Mit Lifetime hast du keine Tageslimits – unbegrenzte Analysen, für immer.", en: "With Lifetime you have no daily limits – unlimited analyses, forever." },
  "upload.unlimitedAnalyses": { de: "Unbegrenzte KI-Analysen", en: "Unlimited AI analyses" },
  "upload.noDailyLimits": { de: "Keine Tageslimits", en: "No daily limits" },
  "upload.oneTimePay": { de: "Einmalzahlung, kein Abo", en: "One-time payment, no subscription" },
  "upload.upgradeLifetime": { de: "Auf Lifetime upgraden", en: "Upgrade to Lifetime" },
  "upload.backToDashboard": { de: "Zurück zum Dashboard", en: "Back to Dashboard" },

  // Analysis Results
  "results.title": { de: "Deine Analyse", en: "Your Analysis" },
  "results.overallScore": { de: "Gesamt-Score", en: "Overall Score" },
  "results.potential": { de: "Potenzial", en: "Potential" },
  "results.strengths": { de: "Stärken", en: "Strengths" },
  "results.weaknesses": { de: "Schwächen", en: "Weaknesses" },
  "results.priorities": { de: "Prioritäten", en: "Priorities" },
  "results.detailedResults": { de: "Detaillierte Ergebnisse", en: "Detailed Results" },
  "results.newAnalysis": { de: "Neue Analyse", en: "New Analysis" },
  "results.viewPlan": { de: "Plan ansehen", en: "View Plan" },
  "results.processing": { de: "Deine Analyse wird verarbeitet...", en: "Your analysis is being processed..." },

  // Friends Page
  "friends.title": { de: "Freunde", en: "Friends" },
  "friends.subtitle": { de: "Erreicht zusammen eure Ziele", en: "Achieve your goals together" },
  "friends.myFriends": { de: "Freunde", en: "Friends" },
  "friends.requests": { de: "Anfragen", en: "Requests" },
  "friends.addFriend": { de: "Freund hinzufügen", en: "Add Friend" },
  "friends.add": { de: "Neu", en: "Add" },
  "friends.partner": { de: "Partner", en: "Partner" },
  "friends.yourCode": { de: "Dein Freundes-Code", en: "Your Friend Code" },
  "friends.shareCode": { de: "Teile diesen Code mit Freunden", en: "Share this code with friends" },
  "friends.enterCode": { de: "Code eingeben", en: "Enter code" },
  "friends.noFriends": { de: "Noch keine Freunde", en: "No friends yet" },
  "friends.noFriendsDesc": { de: "Teile deinen Code oder suche nach anderen Nutzern", en: "Share your code or search for other users" },
  "friends.online": { de: "Online", en: "Online" },
  "friends.offline": { de: "Offline", en: "Offline" },
  "friends.friendsSince": { de: "Freunde seit", en: "Friends since" },
  "friends.message": { de: "Nachricht", en: "Message" },
  "friends.removeFriend": { de: "Freund entfernen", en: "Remove friend" },
  "friends.privacySettings": { de: "Privatsphäre", en: "Privacy" },
  "friends.showScore": { de: "Score anzeigen", en: "Show Score" },
  "friends.showStreak": { de: "Streak anzeigen", en: "Show Streak" },
  "friends.addByCode": { de: "Mit Code hinzufügen", en: "Add by code" },
  "friends.addByCodeDesc": { de: "Gib den 8-stelligen Code ein", en: "Enter the 8-digit code" },
  "friends.searchUsers": { de: "Nutzer suchen", en: "Search users" },
  "friends.searchUsersDesc": { de: "Nach Display-Namen suchen", en: "Search by display name" },
  "friends.searchPlaceholder": { de: "Name eingeben...", en: "Enter name..." },
  "friends.invalidCode": { de: "Ungültiger Code", en: "Invalid code" },
  "friends.invalidCodeDesc": { de: "Bitte gib einen gültigen 8-stelligen Code ein.", en: "Please enter a valid 8-digit code." },
  "friends.codeCopied": { de: "Code kopiert! ✓", en: "Code copied! ✓" },
  "friends.textCopied": { de: "Text kopiert! ✓", en: "Text copied! ✓" },
  "friends.textCopiedDesc": { de: "Teile ihn mit deinen Freunden.", en: "Share it with your friends." },
  "friends.wantsToBePartner": { de: "möchte dein Partner werden", en: "wants to be your partner" },
  "friends.wantsToBeFriend": { de: "möchte dein Freund sein", en: "wants to be your friend" },
  "friends.accept": { de: "Annehmen", en: "Accept" },
  "friends.waitingForReply": { de: "Warten auf Antwort...", en: "Waiting for reply..." },
  "friends.withdraw": { de: "Zurückziehen", en: "Withdraw" },
  "friends.yourRequests": { de: "Deine Anfragen", en: "Your Requests" },
  "friends.partnerRequests": { de: "Partner-Anfragen", en: "Partner Requests" },
  "friends.accountabilityPartner": { de: "Accountability Partner", en: "Accountability Partner" },
  "friends.accountabilityDesc": { de: "Wähle einen Freund als Partner. Checkt täglich gemeinsam ein und motiviert euch gegenseitig!", en: "Choose a friend as a partner. Check in daily together and motivate each other!" },
  "friends.addFriends": { de: "Freunde hinzufügen", en: "Add friends" },

  // Lifestyle Page
  "lifestyle.title": { de: "Tägliches Tracking", en: "Daily Tracking" },
  "lifestyle.subtitle": { de: "Deine Gewohnheiten auf einen Blick", en: "Your habits at a glance" },
  "lifestyle.premiumDesc": { de: "Lifestyle Tracking, Supplements & Ziele nur für Premium.", en: "Lifestyle Tracking, Supplements & Goals for Premium only." },
  "lifestyle.sleep": { de: "Schlaf", en: "Sleep" },
  "lifestyle.water": { de: "Wasser", en: "Water" },
  "lifestyle.exercise": { de: "Training", en: "Exercise" },
  "lifestyle.nutrition": { de: "Ernährung", en: "Nutrition" },
  "lifestyle.supplements": { de: "Supplements", en: "Supplements" },
  "lifestyle.skincare": { de: "Skincare", en: "Skincare" },
  "lifestyle.fasting": { de: "Fasten", en: "Fasting" },
  "lifestyle.mood": { de: "Stimmung", en: "Mood" },
  "lifestyle.lowSleep": { de: "geschlafen – gönn dir mehr Ruhe!", en: "of sleep – get more rest!" },
  "lifestyle.lowWater": { de: "getrunken – trink mehr Wasser!", en: "drunk – drink more water!" },
  "lifestyle.allGood": { de: "Alles im grünen Bereich!", en: "All good!" },
  "lifestyle.allGoodDesc": { de: "Gut geschlafen und genug getrunken.", en: "Slept well and drank enough." },
  "lifestyle.goals": { de: "Ziele", en: "Goals" },
  "lifestyle.challenges": { de: "Challenges", en: "Challenges" },

  // Affiliate Page
  "affiliate.title": { de: "Affiliate Programm", en: "Affiliate Program" },
  "affiliate.subtitle": { de: "Verdiene 20% für jedes vermittelte Abo", en: "Earn 20% for every referred subscription" },
  "affiliate.commission": { de: "20% Provision", en: "20% Commission" },
  "affiliate.onAllSubs": { de: "auf alle vermittelten Abos", en: "on all referred subscriptions" },
  "affiliate.invitations": { de: "Einladungen", en: "Invitations" },
  "affiliate.conversions": { de: "Conversions", en: "Conversions" },
  "affiliate.pending": { de: "Ausstehend", en: "Pending" },
  "affiliate.totalEarnings": { de: "Gesamt", en: "Total" },
  "affiliate.yourLink": { de: "Dein Affiliate-Link", en: "Your Affiliate Link" },
  "affiliate.copyLink": { de: "Link kopieren", en: "Copy link" },
  "affiliate.shareLink": { de: "Link teilen", en: "Share link" },
  "affiliate.requestPayout": { de: "Auszahlung beantragen", en: "Request Payout" },
  "affiliate.payoutProcessing": { de: "Auszahlung in Bearbeitung", en: "Payout processing" },
  "affiliate.payoutProcessingDesc": { de: "Deine Auszahlung von", en: "Your payout of" },
  "affiliate.payoutProcessingDesc2": { de: "wird bearbeitet.", en: "is being processed." },
  "affiliate.minNotReached": { de: "Mindestbetrag nicht erreicht", en: "Minimum not reached" },
  "affiliate.minNotReachedDesc": { de: "Du brauchst mindestens €50 ausstehende Provision. Aktuell:", en: "You need at least €50 pending commission. Currently:" },
  "affiliate.payoutConfirm": { de: "Auszahlung beantragen?", en: "Request payout?" },
  "affiliate.payoutConfirmDesc": { de: "Du beantragst eine Auszahlung von", en: "You are requesting a payout of" },
  "affiliate.payoutConfirmDesc2": { de: "via", en: "via" },
  "affiliate.payoutConfirmDesc3": { de: "Die Bearbeitung kann einige Werktage dauern.", en: "Processing may take a few business days." },
  "affiliate.requesting": { de: "Wird beantragt...", en: "Requesting..." },
  "affiliate.requestNow": { de: "Jetzt beantragen", en: "Request now" },
  "affiliate.savePayoutFirst": { de: "Bitte speichere zuerst deine Auszahlungsdaten unten.", en: "Please save your payout details below first." },
  "affiliate.howItWorks": { de: "So funktioniert's", en: "How it works" },
  "affiliate.step1Title": { de: "Teile deinen Link", en: "Share your link" },
  "affiliate.step1Desc": { de: "Sende deinen persönlichen Affiliate-Link an Freunde oder teile ihn in Social Media.", en: "Send your personal affiliate link to friends or share it on social media." },
  "affiliate.step2Title": { de: "Dein Freund registriert sich", en: "Your friend signs up" },
  "affiliate.step2Desc": { de: "Wenn jemand über deinen Link ein Abo abschließt, wirst du automatisch als Referrer vermerkt.", en: "When someone subscribes through your link, you're automatically recorded as the referrer." },
  "affiliate.step3Title": { de: "Du verdienst 20%", en: "You earn 20%" },
  "affiliate.step3Desc": { de: "Für jede Abo-Zahlung deines geworbenen Nutzers erhältst du 20% Provision.", en: "For every subscription payment from your referred user, you receive 20% commission." },
  "affiliate.payoutSettings": { de: "Auszahlungseinstellungen", en: "Payout Settings" },
  "affiliate.payoutMethod": { de: "Auszahlungsmethode", en: "Payout method" },
  "affiliate.selectMethod": { de: "Methode wählen", en: "Select method" },
  "affiliate.bankTransfer": { de: "Banküberweisung", en: "Bank Transfer" },
  "affiliate.accountHolder": { de: "Kontoinhaber", en: "Account Holder" },
  "affiliate.saveSettings": { de: "Einstellungen speichern", en: "Save settings" },
  "affiliate.payoutMinHint": { de: "Auszahlungen erfolgen ab einem Mindestbetrag von €50 und werden manuell bearbeitet.", en: "Payouts are processed from a minimum of €50 and are handled manually." },
  "affiliate.payoutRequests": { de: "Auszahlungsanfragen", en: "Payout Requests" },
  "affiliate.paid": { de: "Ausgezahlt", en: "Paid" },
  "affiliate.rejected": { de: "Abgelehnt", en: "Rejected" },
  "affiliate.processing": { de: "In Bearbeitung", en: "Processing" },
  "affiliate.note": { de: "Hinweis:", en: "Note:" },
  "affiliate.earningsHistory": { de: "Provisionshistorie", en: "Commission History" },
  "affiliate.noEarnings": { de: "Noch keine Provisionen", en: "No commissions yet" },
  "affiliate.noEarningsDesc": { de: "Teile deinen Link, um zu verdienen!", en: "Share your link to start earning!" },
  "affiliate.commissionLabel": { de: "Provision", en: "Commission" },

  // Gamification - XP Level Card
  "xp.level": { de: "Level", en: "Level" },
  "xp.totalXp": { de: "Total XP", en: "Total XP" },
  "xp.progressTo": { de: "Fortschritt zu Level", en: "Progress to Level" },
  "xp.beginner": { de: "Anfänger", en: "Beginner" },
  "xp.apprentice": { de: "Lehrling", en: "Apprentice" },
  "xp.riser": { de: "Aufsteiger", en: "Rising Star" },
  "xp.veteran": { de: "Veteran", en: "Veteran" },
  "xp.expert": { de: "Experte", en: "Expert" },
  "xp.elite": { de: "Elite", en: "Elite" },
  "xp.master": { de: "Meister", en: "Master" },
  "xp.legend": { de: "Legende", en: "Legend" },

  // Gamification - Daily Challenges
  "challenges.title": { de: "Tägliche Challenges", en: "Daily Challenges" },
  "challenges.completed": { de: "abgeschlossen", en: "completed" },
  "challenges.easy": { de: "Einfach", en: "Easy" },
  "challenges.medium": { de: "Mittel", en: "Medium" },
  "challenges.hard": { de: "Schwer", en: "Hard" },
  "challenges.from20": { de: "ab 20:00", en: "from 8 PM" },
  "challenges.lockedUntil": { de: "Diese Challenge kann erst ab 20:00 Uhr abgeschlossen werden", en: "This challenge can only be completed after 8 PM" },
  "challenges.allDone": { de: "🎉 Alle Challenges abgeschlossen! Komm morgen wieder!", en: "🎉 All challenges completed! Come back tomorrow!" },

  // Product Recommendations
  "products.recommended": { de: "Für dich empfohlen", en: "Recommended for You" },
  "products.basedOn": { de: "Basierend auf deiner Analyse", en: "Based on your analysis" },
  "products.count": { de: "Produkte", en: "Products" },
  "products.showAll": { de: "Alle", en: "All" },
  "products.showAllProducts": { de: "Produkte anzeigen", en: "products" },
  "products.allRecommended": { de: "Alle empfohlenen Produkte", en: "All recommended products" },
  "products.helpsFor": { de: "Hilft bei:", en: "Helps with:" },
  "products.searchOnAmazon": { de: "Auf Amazon suchen", en: "Search on Amazon" },
  "products.topMatch": { de: "Top-Match", en: "Top Match" },
  "products.treatment": { de: "Behandlung", en: "Treatment" },
  "products.exfoliant": { de: "Peeling", en: "Exfoliant" },
  "products.sunscreen": { de: "Sonnenschutz", en: "Sunscreen" },
  "products.haircare": { de: "Haarpflege", en: "Hair Care" },
  "products.tool": { de: "Werkzeug", en: "Tool" },

  // Help Center
  "help.title": { de: "Hilfe-Center", en: "Help Center" },
  "help.subtitle": { de: "Alles was du wissen musst", en: "Everything you need to know" },
  "help.quickstart": { de: "Schnellstart", en: "Quick Start" },
  "help.features": { de: "Features", en: "Features" },
  "help.faq": { de: "FAQ", en: "FAQ" },
  "help.3steps": { de: "3 einfachen Schritten", en: "3 simple steps" },
  "help.toBestSelf": { de: "zu deinem besten Selbst", en: "to your best self" },
  "help.step": { de: "Schritt", en: "Step" },
  "help.step1Title": { de: "Fotos hochladen", en: "Upload photos" },
  "help.step1Desc": { de: "Lade 3 Fotos hoch: frontal, seitlich und ganzkörper. Unsere KI analysiert über 50 Gesichtsmerkmale.", en: "Upload 3 photos: front, side and full body. Our AI analyzes over 50 facial features." },
  "help.step2Title": { de: "Score & Analyse erhalten", en: "Get Score & Analysis" },
  "help.step2Desc": { de: "Du erhältst einen objektiven Score, siehst dein Potential und verstehst deine Stärken und Verbesserungsmöglichkeiten.", en: "You receive an objective score, see your potential and understand your strengths and areas for improvement." },
  "help.step3Title": { de: "Personalisierten Plan umsetzen", en: "Follow Personalized Plan" },
  "help.step3Desc": { de: "Folge deinem maßgeschneiderten Plan mit konkreten, wissenschaftlich fundierten Schritten für sichtbare Verbesserungen.", en: "Follow your tailored plan with concrete, scientifically based steps for visible improvements." },
  "help.startTour": { de: "Interaktive Tour starten", en: "Start Interactive Tour" },
  "help.aiAnalysis": { de: "KI-Analyse", en: "AI Analysis" },
  "help.aiAnalysisDesc": { de: "Objektive Bewertung basierend auf wissenschaftlichen Proportionen", en: "Objective rating based on scientific proportions" },
  "help.personalPlan": { de: "Persönlicher Plan", en: "Personal Plan" },
  "help.personalPlanDesc": { de: "Maßgeschneiderte Empfehlungen für alle Bereiche", en: "Tailored recommendations for all areas" },
  "help.lifestyleTracking": { de: "Lifestyle Tracking", en: "Lifestyle Tracking" },
  "help.lifestyleTrackingDesc": { de: "Tracke Schlaf, Wasser, Ernährung und mehr", en: "Track sleep, water, nutrition and more" },
  "help.progressTracking": { de: "Fortschritt", en: "Progress" },
  "help.progressTrackingDesc": { de: "Verfolge deine Entwicklung über Zeit", en: "Track your development over time" },
  "help.aiCoach": { de: "AI Coach", en: "AI Coach" },
  "help.aiCoachDesc": { de: "Persönlicher Assistent für alle Fragen", en: "Personal assistant for all your questions" },
  "help.community": { de: "Community", en: "Community" },
  "help.communityDesc": { de: "Verbinde dich mit Freunden", en: "Connect with friends" },
  "help.faq1Q": { de: "Wie genau ist die KI-Analyse?", en: "How accurate is the AI analysis?" },
  "help.faq1A": { de: "Die KI analysiert über 50 Gesichtsmerkmale basierend auf wissenschaftlich belegten Attraktivitäts-Standards. Die Genauigkeit liegt bei etwa 85-90% im Vergleich zu menschlichen Bewertungen.", en: "The AI analyzes over 50 facial features based on scientifically proven attractiveness standards. Accuracy is about 85-90% compared to human ratings." },
  "help.faq2Q": { de: "Wie oft sollte ich eine Analyse machen?", en: "How often should I do an analysis?" },
  "help.faq2A": { de: "Wir empfehlen eine neue Analyse alle 4-8 Wochen, um deinen Fortschritt zu tracken. Zu häufige Analysen zeigen keine signifikanten Änderungen.", en: "We recommend a new analysis every 4-8 weeks to track your progress. Too frequent analyses won't show significant changes." },
  "help.faq3Q": { de: "Sind meine Fotos sicher?", en: "Are my photos safe?" },
  "help.faq3A": { de: "Ja! Deine Fotos werden verschlüsselt gespeichert und niemals an Dritte weitergegeben. Du kannst sie jederzeit vollständig löschen.", en: "Yes! Your photos are stored encrypted and never shared with third parties. You can delete them completely at any time." },
  "help.faq4Q": { de: "Was bringt Premium?", en: "What does Premium include?" },
  "help.faq4A": { de: "Mit Premium erhältst du unbegrenzte Analysen, detaillierte Ergebnisse, den AI Coach, alle Lifestyle-Tracker und den personalisierten Plan.", en: "With Premium you get unlimited analyses, detailed results, the AI Coach, all lifestyle trackers and the personalized plan." },
  "help.faq5Q": { de: "Kann ich meinen Score verbessern?", en: "Can I improve my score?" },
  "help.faq5A": { de: "Ja! Die meisten Nutzer verbessern ihren Score um 0.5-2 Punkte innerhalb von 3-6 Monaten durch konsequente Umsetzung des Plans.", en: "Yes! Most users improve their score by 0.5-2 points within 3-6 months through consistent plan implementation." },
  "help.moreQuestions": { de: "Noch Fragen? Zum Support-Center", en: "More questions? Go to Support Center" },

  // Pricing  
  "pricing.backToHome": { de: "Zurück zur Startseite", en: "Back to Home" },

  // Mobile Dashboard
  "mobile.analysis": { de: "Analyse", en: "Analysis" },
  "mobile.plan": { de: "Plan", en: "Plan" },
  "mobile.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "mobile.friends": { de: "Freunde", en: "Friends" },

  // Index/Landing
  "index.loading": { de: "Lade...", en: "Loading..." },
  "index.redirecting": { de: "Weiterleitung...", en: "Redirecting..." },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem("app-language");
      if (stored === "en" || stored === "de") return stored;
    } catch {}
    return "de";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("app-language", lang);
    } catch {}
  }, []);

  const t = useCallback(
    (key: string): string => {
      const entry = translations[key];
      if (!entry) {
        // Fallback: return the key itself (helps spotting missing translations)
        return key;
      }
      return entry[language];
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
