import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "de" | "en";

type Translations = Record<string, Record<Language, string>>;

// Core UI translations
const translations: Translations = {
  // Navigation
  "nav.home": { de: "Home", en: "Home" },
  "nav.progress": { de: "Fortschritt", en: "Progress" },
  "nav.scan": { de: "Scan", en: "Scan" },
  "nav.friends": { de: "Freunde", en: "Friends" },
  "nav.plan": { de: "Plan", en: "Plan" },
  "nav.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "nav.support": { de: "Support", en: "Support" },
  "nav.back": { de: "Zurück", en: "Back" },
  "nav.backToHome": { de: "Zurück zur Startseite", en: "Back to Home" },
  "nav.backToDashboard": { de: "Zurück zum Dashboard", en: "Back to Dashboard" },
  
  // Dashboard
  "dashboard.greeting.morning": { de: "Guten Morgen", en: "Good Morning" },
  "dashboard.greeting.afternoon": { de: "Guten Tag", en: "Good Afternoon" },
  "dashboard.greeting.evening": { de: "Guten Abend", en: "Good Evening" },
  "dashboard.greeting.night": { de: "Gute Nacht", en: "Good Night" },
  "dashboard.score": { de: "Dein Looks Score", en: "Your Looks Score" },
  "dashboard.potential": { de: "Dein Potenzial", en: "Your Potential" },
  "dashboard.streak": { de: "Streak", en: "Streak" },
  "dashboard.level": { de: "Level", en: "Level" },
  "dashboard.scans": { de: "Scans", en: "Scans" },
  "dashboard.quickAccess": { de: "Schnellzugriff", en: "Quick Access" },
  "dashboard.recentAnalyses": { de: "Letzte Analysen", en: "Recent Analyses" },
  "dashboard.all": { de: "Alle", en: "All" },
  "dashboard.startJourney": { de: "Starte deine Reise", en: "Start Your Journey" },
  "dashboard.uploadPhotos": { de: "Lade Fotos hoch und erhalte deine persönliche KI-Analyse", en: "Upload photos and get your personal AI analysis" },
  "dashboard.firstAnalysis": { de: "Erste Analyse starten", en: "Start First Analysis" },
  "dashboard.sinceLastAnalysis": { de: "seit letzter Analyse", en: "since last analysis" },
  "dashboard.progress": { de: "Fortschritt", en: "Progress" },
  "dashboard.reachable": { de: "erreichbar", en: "reachable" },
  "dashboard.personalBest": { de: "Bestwert", en: "Personal Best" },
  "dashboard.yourProgress": { de: "Dein Fortschritt", en: "Your Progress" },
  "dashboard.pointsReachable": { de: "Punkte", en: "Points" },
  "dashboard.outOf": { de: "von", en: "of" },
  "dashboard.share": { de: "Teilen", en: "Share" },
  "dashboard.nextSteps": { de: "Nächste Schritte", en: "Next Steps" },
  "dashboard.revenueAndSubs": { de: "Umsatz & Abos", en: "Revenue & Subs" },
  "dashboard.revenueDesc": { de: "Revenue & Affiliate-Übersicht", en: "Revenue & Affiliate Overview" },
  "dashboard.analyses": { de: "Analysen", en: "Analyses" },
  "dashboard.ranking": { de: "Ranking", en: "Ranking" },
  "dashboard.activeToday": { de: "Heute aktiv werden!", en: "Get active today!" },
  "dashboard.onFire": { de: "🔥 On Fire!", en: "🔥 On Fire!" },
  "dashboard.resultLocked": { de: "Ergebnis gesperrt", en: "Result locked" },
  "dashboard.unlock": { de: "Freischalten", en: "Unlock" },
  "dashboard.progressToPotential": { de: "Fortschritt zu deinem Potenzial", en: "Progress to your potential" },
  "dashboard.pointsPossible": { de: "möglich", en: "possible" },
  "dashboard.viewPlan": { de: "Plan ansehen", en: "View Plan" },
  "dashboard.scoreChart": { de: "Score-Entwicklung", en: "Score Progression" },
  "dashboard.chartLocked": { de: "Chart gesperrt", en: "Chart locked" },
  "dashboard.potential_label": { de: "Potenzial", en: "Potential" },
  "dashboard.premiumFeature": { de: "Premium Feature", en: "Premium Feature" },
  "dashboard.unlockAll": { de: "Schalte alle Features frei", en: "Unlock all features" },
  "dashboard.unlockAllDesc": { de: "Erhalte detaillierte Analysen, deinen personalisierten Plan und Zugang zum AI Coach.", en: "Get detailed analyses, your personalized plan, and access to the AI Coach." },
  "dashboard.goPremium": { de: "Premium werden", en: "Go Premium" },
  "dashboard.noAnalyses": { de: "Noch keine Analysen", en: "No analyses yet" },
  "dashboard.noAnalysesDesc": { de: "Lade ein Foto hoch und erhalte in wenigen Sekunden deinen Looks Score.", en: "Upload a photo and get your Looks Score in seconds." },
  "dashboard.startNewAnalysis": { de: "Neue Analyse starten", en: "Start New Analysis" },
  "dashboard.trackProgress": { de: "Tracke deinen Fortschritt mit regelmäßigen Analysen.", en: "Track your progress with regular analyses." },
  "dashboard.analyzePhoto": { de: "Foto analysieren", en: "Analyze Photo" },
  "dashboard.analysisComplete": { de: "Analyse abgeschlossen", en: "Analysis complete" },
  "dashboard.analyzing": { de: "Wird analysiert...", en: "Analyzing..." },
  "dashboard.validationFailed": { de: "Validierung fehlgeschlagen", en: "Validation failed" },
  "dashboard.failed": { de: "Fehlgeschlagen", en: "Failed" },
  "dashboard.pending": { de: "Ausstehend", en: "Pending" },
  "dashboard.top": { de: "Top", en: "Top" },
  "dashboard.average": { de: "Durchschnitt", en: "Average" },
  "dashboard.potential_badge": { de: "Potenzial", en: "Potential" },
  "dashboard.inProgress": { de: "In Bearbeitung", en: "In Progress" },
  "dashboard.more": { de: "mehr", en: "more" },
  "dashboard.showAll": { de: "anzeigen", en: "show" },
  "dashboard.analysesLocked": { de: "Analysen gesperrt", en: "Analyses locked" },
  "dashboard.noOpenTasks": { de: "Keine offenen Tasks", en: "No open tasks" },
  "dashboard.createPlan": { de: "Plan erstellen", en: "Create Plan" },
  "dashboard.unlockPremium": { de: "Premium freischalten", en: "Unlock Premium" },
  "dashboard.recommendedProducts": { de: "Empfohlene Produkte für dich", en: "Recommended Products for You" },
  "dashboard.achievements": { de: "Achievements", en: "Achievements" },
  "dashboard.achievementsDesc": { de: "Schalte Belohnungen frei und tracke deinen Fortschritt", en: "Unlock rewards and track your progress" },
  
  // Delete Dialog
  "dialog.cancelAnalysis": { de: "Analyse abbrechen?", en: "Cancel analysis?" },
  "dialog.removeAnalysis": { de: "Analyse entfernen?", en: "Remove analysis?" },
  "dialog.cancelAnalysisDesc": { de: "Diese laufende Analyse wird abgebrochen und gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.", en: "This running analysis will be cancelled and deleted. This action cannot be undone." },
  "dialog.removeAnalysisDesc": { de: "Diese fehlgeschlagene Analyse wird aus deiner Historie entfernt. Diese Aktion kann nicht rückgängig gemacht werden.", en: "This failed analysis will be removed from your history. This action cannot be undone." },
  "dialog.cancelBtn": { de: "Abbrechen", en: "Cancel" },
  "dialog.cancelAnalysisBtn": { de: "Analyse abbrechen", en: "Cancel Analysis" },
  "dialog.removeAnalysisBtn": { de: "Analyse entfernen", en: "Remove Analysis" },
  "dialog.analysisCancelled": { de: "Analyse abgebrochen", en: "Analysis cancelled" },
  "dialog.analysisRemoved": { de: "Analyse entfernt", en: "Analysis removed" },
  "dialog.analysisDeleted": { de: "Die Analyse wurde erfolgreich gelöscht.", en: "The analysis was successfully deleted." },
  "dialog.error": { de: "Fehler", en: "Error" },
  "dialog.deleteError": { de: "Die Analyse konnte nicht gelöscht werden.", en: "The analysis could not be deleted." },
  
  // Quick Actions
  "quick.newAnalysis": { de: "Neue Analyse", en: "New Analysis" },
  "quick.newAnalysisDesc": { de: "Lade Fotos hoch für deine KI-Bewertung", en: "Upload photos for your AI rating" },
  "quick.myPlan": { de: "Mein Plan", en: "My Plan" },
  "quick.myPlanDesc": { de: "Dein personalisierter Looksmax-Plan", en: "Your personalized looksmax plan" },
  "quick.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "quick.lifestyleDesc": { de: "Tracke Schlaf, Wasser & Supplements", en: "Track sleep, water & supplements" },
  "quick.friends": { de: "Freunde", en: "Friends" },
  "quick.friendsDesc": { de: "Verbinde dich mit anderen", en: "Connect with others" },
  "quick.progress": { de: "Fortschritt", en: "Progress" },
  "quick.progressDesc": { de: "Verfolge deine Entwicklung", en: "Track your development" },
  "quick.affiliate": { de: "Affiliate", en: "Affiliate" },
  "quick.affiliateDesc": { de: "Verdiene 20% pro Abo", en: "Earn 20% per subscription" },
  "quick.skinType": { de: "Hauttyp erkennen", en: "Detect Skin Type" },
  "quick.skinTypeDesc": { de: "KI-gestützte Hautanalyse", en: "AI-powered skin analysis" },
  
  // Subscription
  "sub.premiumUntil": { de: "Premium bis", en: "Premium until" },
  
  // Analysis
  "analysis.new": { de: "Neue Analyse", en: "New Analysis" },
  "analysis.description": { de: "Lade Fotos hoch für deine KI-Bewertung", en: "Upload photos for your AI rating" },
  
  // Common
  "common.loading": { de: "Wird geladen...", en: "Loading..." },
  "common.save": { de: "Speichern", en: "Save" },
  "common.cancel": { de: "Abbrechen", en: "Cancel" },
  "common.close": { de: "Schließen", en: "Close" },
  "common.delete": { de: "Löschen", en: "Delete" },
  "common.edit": { de: "Bearbeiten", en: "Edit" },
  "common.share": { de: "Teilen", en: "Share" },
  "common.premium": { de: "Premium", en: "Premium" },
  "common.free": { de: "Kostenlos", en: "Free" },
  "common.or": { de: "oder", en: "or" },
  "common.refresh": { de: "Aktualisieren", en: "Refresh" },
  "common.retry": { de: "Erneut versuchen", en: "Try again" },
  "common.error": { de: "Fehler", en: "Error" },
  "common.success": { de: "Erfolg", en: "Success" },
  "common.confirm": { de: "Bestätigen", en: "Confirm" },
  "common.yes": { de: "Ja", en: "Yes" },
  "common.no": { de: "Nein", en: "No" },
  "common.search": { de: "Suchen", en: "Search" },
  "common.send": { de: "Senden", en: "Send" },
  "common.copy": { de: "Kopieren", en: "Copy" },
  "common.copied": { de: "Kopiert!", en: "Copied!" },
  
  // Profile
  "profile.edit": { de: "Profil bearbeiten", en: "Edit Profile" },
  "profile.settings": { de: "Design anpassen", en: "Customize Design" },
  "profile.security": { de: "Sicherheit", en: "Security" },
  "profile.logout": { de: "Ausloggen", en: "Log Out" },
  
  // Notifications
  "notifications.title": { de: "Benachrichtigungen", en: "Notifications" },
  "notifications.empty": { de: "Keine neuen Benachrichtigungen", en: "No new notifications" },
  "notifications.unreadMessages": { de: "Ungelesene Nachrichten", en: "Unread Messages" },
  "notifications.friendRequests": { de: "Freundschaftsanfragen", en: "Friend Requests" },
  "notifications.partnerRequests": { de: "Partner-Anfragen", en: "Partner Requests" },

  // Motivation
  "motivation.readyForProgress": { de: "Bereit für einen weiteren Tag voller Fortschritt? 💪", en: "Ready for another day of progress? 💪" },
  
  // Language
  "language.de": { de: "Deutsch", en: "German" },
  "language.en": { de: "Englisch", en: "English" },

  // Skin Type Analyzer
  "skin.detect": { de: "Hauttyp erkennen", en: "Detect Skin Type" },
  "skin.title": { de: "AI Hauttyp-Erkennung", en: "AI Skin Type Detection" },
  "skin.description": { de: "Lade ein Nahaufnahme-Foto deines Gesichts hoch für eine KI-gestützte Hauttyp-Analyse.", en: "Upload a close-up photo of your face for an AI-powered skin type analysis." },
  "skin.upload": { de: "Tippe hier, um ein Foto hochzuladen", en: "Tap here to upload a photo" },
  "skin.uploadTip": { de: "Am besten: Nahaufnahme, gutes Licht, kein Make-up", en: "Best: close-up, good lighting, no makeup" },
  "skin.analyzing": { de: "Hauttyp wird analysiert...", en: "Analyzing skin type..." },
  "skin.confidence": { de: "Sicherheit", en: "Confidence" },
  "skin.characteristics": { de: "Merkmale", en: "Characteristics" },
  "skin.recommendations": { de: "Empfohlene Produkte", en: "Recommended Products" },
  "skin.tips": { de: "Tipps", en: "Tips" },
  "skin.retry": { de: "Neue Analyse", en: "New Analysis" },
  "skin.error": { de: "Analyse fehlgeschlagen", en: "Analysis failed" },

  // Login Page
  "login.welcome": { de: "Willkommen zurück", en: "Welcome back" },
  "login.subtitle": { de: "Melde dich an, um fortzufahren", en: "Sign in to continue" },
  "login.subtitleDesktop": { de: "Melde dich an, um deinen Fortschritt zu tracken.", en: "Sign in to track your progress." },
  "login.email": { de: "E-Mail", en: "Email" },
  "login.password": { de: "Passwort", en: "Password" },
  "login.forgot": { de: "Vergessen?", en: "Forgot?" },
  "login.submit": { de: "Anmelden", en: "Sign In" },
  "login.submitting": { de: "Anmelden...", en: "Signing in..." },
  "login.googleLogin": { de: "Mit Google anmelden", en: "Sign in with Google" },
  "login.googleConnecting": { de: "Verbinde...", en: "Connecting..." },
  "login.googleConnectingFull": { de: "Verbinde mit Google...", en: "Connecting with Google..." },
  "login.noAccount": { de: "Noch kein Konto?", en: "Don't have an account?" },
  "login.register": { de: "Jetzt registrieren", en: "Register now" },
  "login.accountLocked": { de: "Konto gesperrt", en: "Account locked" },
  "login.tooManyAttempts": { de: "Zu viele Fehlversuche", en: "Too many failed attempts" },
  "login.accountLockedDesc": { de: "Dein Konto ist vorübergehend gesperrt. Bitte warte", en: "Your account is temporarily locked. Please wait" },
  "login.attemptsRemaining": { de: "Versuche verbleibend", en: "attempts remaining" },
  "login.attemptsBeforeLock": { de: "bevor dein Konto für 5 Minuten gesperrt wird.", en: "before your account is locked for 5 minutes." },
  "login.forgotPasswordReset": { de: "Passwort vergessen? Jetzt zurücksetzen", en: "Forgot password? Reset now" },
  "login.failed": { de: "Anmeldung fehlgeschlagen", en: "Login failed" },
  "login.wrongCredentials": { de: "E-Mail oder Passwort ist falsch. Wenn du dein Passwort vergessen hast, nutze 'Vergessen?'.", en: "Email or password is incorrect. If you forgot your password, use 'Forgot?'." },
  "login.emailNotConfirmed": { de: "E-Mail nicht bestätigt", en: "Email not confirmed" },
  "login.emailNotConfirmedDesc": { de: "Bitte bestätige zuerst deine E-Mail-Adresse. Überprüfe deinen Posteingang.", en: "Please confirm your email address first. Check your inbox." },
  "login.tooManyRequests": { de: "Zu viele Anfragen", en: "Too many requests" },
  "login.tooManyRequestsDesc": { de: "Bitte warte 1-2 Minuten und versuche es dann erneut.", en: "Please wait 1-2 minutes and try again." },
  "login.welcomeBack": { de: "Willkommen zurück!", en: "Welcome back!" },
  "login.redirecting": { de: "Du wirst zum Dashboard weitergeleitet.", en: "You are being redirected to the dashboard." },
  "login.potentialWaiting": { de: "Dein Potenzial wartet", en: "Your potential awaits" },
  "login.trackProgressGoal": { de: "Tracke deinen Fortschritt und erreiche deinen Ziel-Score.", en: "Track your progress and reach your goal score." },
  "login.lockedFor": { de: "Konto für", en: "Account locked for" },
  "login.locked": { de: "gesperrt.", en: "locked." },
  "login.googleFailed": { de: "Google-Anmeldung fehlgeschlagen", en: "Google sign-in failed" },
  "login.pleaseWait": { de: "Bitte warten", en: "Please wait" },
  "login.waitAndRetry": { de: "Bitte warte und versuche es dann erneut.", en: "Please wait and try again." },

  // Register Page
  "register.title": { de: "Konto erstellen", en: "Create Account" },
  "register.subtitle": { de: "Starte kostenlos – keine Kreditkarte nötig", en: "Start for free – no credit card required" },
  "register.subtitleDesktop": { de: "Starte kostenlos – keine Kreditkarte erforderlich.", en: "Start for free – no credit card required." },
  "register.firstName": { de: "Vorname", en: "First Name" },
  "register.lastName": { de: "Nachname", en: "Last Name" },
  "register.displayName": { de: "Anzeigename", en: "Display Name" },
  "register.displayNamePlaceholder": { de: "Dein Anzeigename", en: "Your display name" },
  "register.displayNameHint": { de: "Dieser Name wird öffentlich angezeigt. Du kannst ihn später ändern.", en: "This name is shown publicly. You can change it later." },
  "register.email": { de: "E-Mail", en: "Email" },
  "register.password": { de: "Passwort", en: "Password" },
  "register.passwordMin": { de: "Mind. 8 Zeichen", en: "Min. 8 characters" },
  "register.confirmPassword": { de: "Passwort bestätigen", en: "Confirm Password" },
  "register.confirmPasswordPlaceholder": { de: "Passwort wiederholen", en: "Repeat password" },
  "register.passwordMismatch": { de: "Passwörter stimmen nicht überein", en: "Passwords don't match" },
  "register.referralCode": { de: "Freundescode (optional)", en: "Referral Code (optional)" },
  "register.referralCodeHint": { de: "Hast du einen Code von einem Freund erhalten?", en: "Did you receive a code from a friend?" },
  "register.referralCodeHintDesktop": { de: "Hast du einen Code von einem Freund erhalten? Gib ihn hier ein!", en: "Did you receive a code from a friend? Enter it here!" },
  "register.submit": { de: "Registrieren", en: "Register" },
  "register.submitDesktop": { de: "Kostenlos registrieren", en: "Register for free" },
  "register.submitting": { de: "Registrieren...", en: "Registering..." },
  "register.submittingDesktop": { de: "Wird erstellt...", en: "Creating..." },
  "register.googleRegister": { de: "Mit Google registrieren", en: "Sign up with Google" },
  "register.connecting": { de: "Verbinde...", en: "Connecting..." },
  "register.hasAccount": { de: "Bereits registriert?", en: "Already registered?" },
  "register.loginNow": { de: "Jetzt anmelden", en: "Sign in now" },
  "register.termsPrefix": { de: "Mit der Registrierung akzeptierst du unsere", en: "By registering you accept our" },
  "register.termsLink": { de: "AGB", en: "Terms" },
  "register.termsAnd": { de: "und", en: "and" },
  "register.privacyLink": { de: "Datenschutz", en: "Privacy Policy" },
  "register.nameHint": { de: "Dein echter Name wird privat gespeichert und ist nur für dich sichtbar.", en: "Your real name is stored privately and is only visible to you." },
  "register.onlyLetters": { de: "Nur Buchstaben erlaubt (keine Zahlen oder Sonderzeichen)", en: "Only letters allowed (no numbers or special characters)" },
  "register.startTransformation": { de: "Starte deine", en: "Start your" },
  "register.transformation": { de: "Transformation", en: "Transformation" },
  "register.invalidName": { de: "Ungültiger Name", en: "Invalid name" },
  "register.invalidNameDesc": { de: "Vor- und Nachname dürfen nur Buchstaben enthalten.", en: "First and last name may only contain letters." },
  "register.missingFields": { de: "Fehlende Angaben", en: "Missing information" },
  "register.missingFieldsDesc": { de: "Bitte gib deinen Vor- und Nachnamen ein.", en: "Please enter your first and last name." },
  "register.invalidDisplayName": { de: "Ungültiger Anzeigename", en: "Invalid display name" },
  "register.nameUnavailable": { de: "Name nicht verfügbar", en: "Name unavailable" },
  "register.nameUnavailableDesc": { de: "Dieser Anzeigename ist bereits vergeben. Bitte wähle einen anderen.", en: "This display name is already taken. Please choose another." },
  "register.emailExists": { de: "E-Mail bereits registriert", en: "Email already registered" },
  "register.emailExistsDesc": { de: "Diese E-Mail existiert bereits. Falls du noch keine Bestätigung hast, sende die Bestätigungs-Mail erneut.", en: "This email already exists. If you haven't confirmed yet, resend the confirmation email." },
  "register.accountCreated": { de: "Konto erstellt!", en: "Account created!" },
  "register.canLogin": { de: "Du kannst dich jetzt anmelden.", en: "You can now sign in." },
  "register.failedTitle": { de: "Registrierung fehlgeschlagen", en: "Registration failed" },
  "register.rateLimitTitle": { de: "Zu viele Anfragen", en: "Too many requests" },
  "register.rateLimitDesc": { de: "Das E-Mail-Limit wurde erreicht. Bitte warte ca. 1 Stunde oder verwende eine andere E-Mail-Adresse.", en: "The email limit has been reached. Please wait about 1 hour or use a different email address." },
  "register.weakPassword": { de: "Unsicheres Passwort", en: "Weak password" },
  "register.weakPasswordDesc": { de: "Dieses Passwort wurde in Datenlecks gefunden und ist nicht sicher. Bitte wähle ein anderes, einzigartiges Passwort.", en: "This password was found in data breaches and is not secure. Please choose a different, unique password." },
  "register.googleFailed": { de: "Google-Registrierung fehlgeschlagen", en: "Google registration failed" },
  "register.passwordStrength.veryWeak": { de: "Sehr schwach", en: "Very weak" },
  "register.passwordStrength.weak": { de: "Schwach", en: "Weak" },
  "register.passwordStrength.medium": { de: "Mittel", en: "Medium" },
  "register.passwordStrength.strong": { de: "Stark", en: "Strong" },
  "register.passwordStrength.veryStrong": { de: "Sehr stark", en: "Very strong" },
  "register.passwordStrength.label": { de: "Passwortstärke:", en: "Password strength:" },
  "register.passwordReq.min8": { de: "Mindestens 8 Zeichen", en: "At least 8 characters" },
  "register.passwordReq.cases": { de: "Groß- und Kleinbuchstaben", en: "Upper and lowercase letters" },
  "register.passwordReq.number": { de: "Mindestens eine Zahl", en: "At least one number" },
  "register.passwordReq.special": { de: "Sonderzeichen (z.B. !@#$)", en: "Special character (e.g. !@#$)" },
  "register.passwordReq.breach": { de: "Passwörter aus Datenlecks werden abgelehnt", en: "Passwords from data breaches will be rejected" },
  "register.benefit1": { de: "KI-Analyse deines Aussehens", en: "AI analysis of your appearance" },
  "register.benefit2": { de: "Personalisierter Looksmax-Plan", en: "Personalized looksmax plan" },
  "register.benefit3": { de: "Progress Tracking mit Streak-System", en: "Progress tracking with streak system" },
  "register.benefit4": { de: "Zugang zum AI Coach", en: "Access to AI Coach" },

  // Forgot Password
  "forgot.title": { de: "Passwort vergessen", en: "Forgot Password" },
  "forgot.subtitle": { de: "Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen.", en: "Enter your email address and we'll send you a reset link." },
  "forgot.email": { de: "E-Mail-Adresse", en: "Email address" },
  "forgot.submit": { de: "Link senden", en: "Send link" },
  "forgot.submitting": { de: "Wird gesendet...", en: "Sending..." },
  "forgot.sent": { de: "E-Mail gesendet!", en: "Email sent!" },
  "forgot.sentDesc": { de: "Wenn ein Konto mit dieser E-Mail existiert, erhältst du einen Reset-Link.", en: "If an account with this email exists, you'll receive a reset link." },
  "forgot.checkInbox": { de: "Überprüfe deinen Posteingang", en: "Check your inbox" },
  "forgot.backToLogin": { de: "Zurück zum Login", en: "Back to login" },
  "forgot.waitCooldown": { de: "Bitte warten", en: "Please wait" },
  "forgot.waitCooldownDesc": { de: "Du kannst in {seconds} Sekunden erneut eine E-Mail anfordern.", en: "You can request another email in {seconds} seconds." },
  "forgot.tooManyRequests": { de: "Zu viele Anfragen. Bitte warte einen Moment und versuche es erneut.", en: "Too many requests. Please wait a moment and try again." },
  "forgot.error": { de: "E-Mail konnte nicht gesendet werden. Bitte versuche es erneut.", en: "Email could not be sent. Please try again." },
  "forgot.resend": { de: "Erneut senden", en: "Resend" },
  "forgot.resendIn": { de: "Erneut senden in", en: "Resend in" },

  // Progress Page
  "progress.title": { de: "Dein Fortschritt", en: "Your Progress" },
  "progress.subtitle": { de: "Verfolge deine Entwicklung über Zeit", en: "Track your development over time" },
  "progress.analyses": { de: "Analysen", en: "analyses" },
  "progress.loading": { de: "Lade Analysen...", en: "Loading analyses..." },
  "progress.noAnalyses": { de: "Keine Analysen vorhanden", en: "No analyses available" },
  "progress.noAnalysesDesc": { de: "Starte deine erste Analyse, um deinen Fortschritt zu tracken.", en: "Start your first analysis to track your progress." },
  "progress.firstAnalysis": { de: "Erste Analyse starten", en: "Start first analysis" },
  "progress.current": { de: "Aktuell", en: "Current" },
  "progress.potential": { de: "Potenzial", en: "Potential" },
  "progress.possible": { de: "möglich", en: "possible" },
  "progress.avgScore": { de: "Durchschnitt", en: "Average" },
  "progress.highest": { de: "Höchster", en: "Highest" },
  "progress.total": { de: "Gesamt", en: "Total" },
  "progress.scoreChart": { de: "Score-Entwicklung", en: "Score Progression" },
  "progress.totalAnalyses": { de: "Analysen total", en: "total analyses" },
  "progress.score": { de: "Score", en: "Score" },
  "progress.premiumTitle": { de: "Premium Feature", en: "Premium Feature" },
  "progress.premiumDesc": { de: "Verfolge deinen Fortschritt mit Vorher/Nachher-Vergleichen und detaillierten Statistiken.", en: "Track your progress with before/after comparisons and detailed statistics." },
  "progress.premiumFeature1": { de: "Vorher/Nachher Fotovergleich", en: "Before/After photo comparison" },
  "progress.premiumFeature2": { de: "Score-Entwicklung über Zeit", en: "Score progression over time" },
  "progress.premiumFeature3": { de: "Detaillierte Statistiken", en: "Detailed statistics" },
  "progress.premiumFeature4": { de: "Stärken & Schwächen Trends", en: "Strengths & Weaknesses Trends" },
  "progress.goPremium": { de: "Jetzt Premium werden", en: "Go Premium now" },
  "progress.beforeAfter": { de: "Vorher / Nachher", en: "Before / After" },
  "progress.before": { de: "Vorher", en: "Before" },
  "progress.after": { de: "Nachher", en: "After" },
  "progress.compareTitle": { de: "Vergleich", en: "Comparison" },
  "progress.skinQuality": { de: "Hautqualität", en: "Skin Quality" },
  "progress.hairStyling": { de: "Haare & Styling", en: "Hair & Styling" },
  "progress.jawlineBody": { de: "Jawline & Body", en: "Jawline & Body" },
  "progress.eyeArea": { de: "Augenbereich", en: "Eye Area" },
  "progress.couldNotLoad": { de: "Analysen konnten nicht geladen werden.", en: "Analyses could not be loaded." },
  
  // Plan Page
  "plan.title": { de: "Dein Looksmax-Plan", en: "Your Looksmax Plan" },
  "plan.subtitle": { de: "Personalisiert basierend auf deiner Analyse", en: "Personalized based on your analysis" },
  "plan.subtitleScore": { de: "Score:", en: "Score:" },
  "plan.subtitleNoAnalysis": { de: "Starte eine Analyse für einen personalisierten Plan.", en: "Start an analysis for a personalized plan." },
  "plan.noAnalysis": { de: "Keine Analyse vorhanden", en: "No analysis available" },
  "plan.noAnalysisDesc": { de: "Mache zuerst eine Analyse, damit wir deinen Plan personalisieren können.", en: "Do an analysis first so we can personalize your plan." },
  "plan.generate": { de: "Plan erstellen", en: "Generate Plan" },
  "plan.generating": { de: "Plan wird erstellt...", en: "Generating plan..." },
  "plan.generated": { de: "Plan erstellt! 🎯", en: "Plan created! 🎯" },
  "plan.generatedDesc": { de: "Dein personalisierter Looksmax-Plan basiert auf deiner Analyse.", en: "Your personalized looksmax plan is based on your analysis." },
  "plan.yourSubScores": { de: "Deine Teil-Scores", en: "Your Sub-Scores" },
  "plan.premiumDesc": { de: "Der personalisierte Looksmax-Plan ist nur für Premium-Mitglieder verfügbar. Erhalte deinen maßgeschneiderten Verbesserungsplan.", en: "The personalized looksmax plan is only available for premium members. Get your tailored improvement plan." },
  "plan.goPremium": { de: "Premium werden", en: "Go Premium" },
  "plan.focusAreas": { de: "Fokus-Bereiche", en: "Focus Areas" },
  "plan.skincare": { de: "Skincare", en: "Skincare" },
  "plan.hairBeard": { de: "Haare & Bart", en: "Hair & Beard" },
  "plan.bodyGym": { de: "Körper & Gym", en: "Body & Gym" },
  "plan.styleClothing": { de: "Style & Kleidung", en: "Style & Clothing" },
  "plan.teethSmile": { de: "Zähne & Lächeln", en: "Teeth & Smile" },
  "plan.mindsetPosture": { de: "Mindset & Haltung", en: "Mindset & Posture" },
  "plan.symmetry": { de: "Symmetrie", en: "Symmetry" },
  "plan.jawline": { de: "Jawline", en: "Jawline" },
  "plan.eyes": { de: "Augen", en: "Eyes" },
  "plan.skin": { de: "Haut", en: "Skin" },
  "plan.hair": { de: "Haare", en: "Hair" },
  "plan.charisma": { de: "Ausstrahlung", en: "Charisma" },

  // Coach Page
  "coach.title": { de: "AI Coach", en: "AI Coach" },
  "coach.greeting": { de: "Frag mich, was du verbessern kannst.", en: "Ask me what you can improve." },
  "coach.placeholder": { de: "Schreib eine Nachricht...", en: "Write a message..." },
  "coach.premiumTitle": { de: "Premium Feature", en: "Premium Feature" },
  "coach.premiumDesc": { de: "Der AI Coach hilft dir mit personalisierten Tipps und Empfehlungen.", en: "The AI Coach helps you with personalized tips and recommendations." },
  "coach.newChat": { de: "Neues Gespräch", en: "New Conversation" },
  "coach.deleted": { de: "Gespräch gelöscht", en: "Conversation deleted" },
  "coach.allDeleted": { de: "Alle Gespräche gelöscht", en: "All conversations deleted" },
  "coach.archived": { de: "Gespräch archiviert", en: "Conversation archived" },
  "coach.unarchived": { de: "Gespräch wiederhergestellt", en: "Conversation restored" },
  "coach.renamed": { de: "Gespräch umbenannt", en: "Conversation renamed" },
  "coach.micBlocked": { de: "Mikrofon blockiert", en: "Microphone blocked" },
  "coach.micBlockedDesc": { de: "Bitte erlaube den Zugriff auf dein Mikrofon.", en: "Please allow microphone access." },
  "coach.noSpeech": { de: "Keine Sprache erkannt", en: "No speech detected" },
  "coach.noSpeechDesc": { de: "Bitte sprich lauter / näher ans Mikrofon und versuche es erneut.", en: "Please speak louder / closer to the microphone and try again." },
  "coach.micUnavailable": { de: "Mikrofon nicht verfügbar", en: "Microphone unavailable" },
  "coach.suggestion1": { de: "Was sollte ich zuerst verbessern?", en: "What should I improve first?" },
  "coach.suggestion2": { de: "Skincare Routine für Anfänger", en: "Skincare routine for beginners" },
  "coach.suggestion3": { de: "Wie verbessere ich meine Jawline?", en: "How do I improve my jawline?" },

  // Support Page
  "support.title": { de: "Support", en: "Support" },
  "support.newTicket": { de: "Neues Ticket", en: "New Ticket" },
  "support.myTickets": { de: "Meine Tickets", en: "My Tickets" },
  "support.subject": { de: "Betreff", en: "Subject" },
  "support.message": { de: "Nachricht", en: "Message" },
  "support.category": { de: "Kategorie", en: "Category" },
  "support.priority": { de: "Priorität", en: "Priority" },
  "support.technical": { de: "Technisches Problem", en: "Technical Issue" },
  "support.billing": { de: "Zahlung & Abrechnung", en: "Billing & Payments" },
  "support.account": { de: "Konto & Profil", en: "Account & Profile" },
  "support.other": { de: "Sonstiges", en: "Other" },
  "support.open": { de: "Offen", en: "Open" },
  "support.inProgress": { de: "In Bearbeitung", en: "In Progress" },
  "support.resolved": { de: "Gelöst", en: "Resolved" },
  "support.closed": { de: "Geschlossen", en: "Closed" },
  "support.noTickets": { de: "Noch keine Tickets", en: "No tickets yet" },
  "support.noTicketsDesc": { de: "Erstelle ein Ticket, wenn du Hilfe brauchst.", en: "Create a ticket when you need help." },
  "support.sendMessage": { de: "Nachricht senden", en: "Send message" },
  "support.noMessages": { de: "Noch keine Nachrichten", en: "No messages yet" },
  "support.supportTeam": { de: "Support-Team", en: "Support Team" },
  "support.you": { de: "Du", en: "You" },

  // Upload Page
  "upload.title": { de: "Neue Analyse", en: "New Analysis" },
  "upload.subtitle": { de: "Lade deine Fotos hoch", en: "Upload your photos" },
  "upload.front": { de: "Frontal", en: "Front" },
  "upload.frontDesc": { de: "Gesicht von vorne", en: "Face from the front" },
  "upload.side": { de: "Seite", en: "Side" },
  "upload.sideDesc": { de: "Profil-Ansicht", en: "Profile view" },
  "upload.body": { de: "Körper", en: "Body" },
  "upload.bodyDesc": { de: "Ganzkörper (optional)", en: "Full body (optional)" },
  "upload.analyze": { de: "Analyse starten", en: "Start Analysis" },
  "upload.analyzing": { de: "Wird analysiert...", en: "Analyzing..." },
  "upload.guidelines": { de: "Foto-Richtlinien", en: "Photo Guidelines" },
  "upload.dailyLimit": { de: "Tägliches Limit erreicht", en: "Daily limit reached" },
  "upload.dropHere": { de: "Fotos hier ablegen", en: "Drop photos here" },

  // Analysis Results
  "results.title": { de: "Deine Analyse", en: "Your Analysis" },
  "results.overallScore": { de: "Gesamt-Score", en: "Overall Score" },
  "results.potential": { de: "Potenzial", en: "Potential" },
  "results.strengths": { de: "Stärken", en: "Strengths" },
  "results.weaknesses": { de: "Schwächen", en: "Weaknesses" },
  "results.priorities": { de: "Prioritäten", en: "Priorities" },
  "results.detailedResults": { de: "Detaillierte Ergebnisse", en: "Detailed Results" },
  "results.newAnalysis": { de: "Neue Analyse", en: "New Analysis" },
  "results.viewPlan": { de: "Plan ansehen", en: "View Plan" },
  "results.processing": { de: "Deine Analyse wird verarbeitet...", en: "Your analysis is being processed..." },

  // Friends Page
  "friends.title": { de: "Freunde", en: "Friends" },
  "friends.myFriends": { de: "Meine Freunde", en: "My Friends" },
  "friends.requests": { de: "Anfragen", en: "Requests" },
  "friends.addFriend": { de: "Freund hinzufügen", en: "Add Friend" },
  "friends.yourCode": { de: "Dein Code", en: "Your Code" },
  "friends.enterCode": { de: "Code eingeben", en: "Enter code" },
  "friends.noFriends": { de: "Noch keine Freunde", en: "No friends yet" },
  "friends.noFriendsDesc": { de: "Teile deinen Code mit Freunden!", en: "Share your code with friends!" },
  "friends.online": { de: "Online", en: "Online" },
  "friends.offline": { de: "Offline", en: "Offline" },
  "friends.message": { de: "Nachricht", en: "Message" },
  "friends.removeFriend": { de: "Freund entfernen", en: "Remove friend" },
  "friends.partner": { de: "Partner", en: "Partner" },
  "friends.privacySettings": { de: "Privatsphäre", en: "Privacy" },
  "friends.showScore": { de: "Score anzeigen", en: "Show Score" },
  "friends.showStreak": { de: "Streak anzeigen", en: "Show Streak" },

  // Lifestyle Page
  "lifestyle.title": { de: "Lifestyle Tracker", en: "Lifestyle Tracker" },
  "lifestyle.premiumDesc": { de: "Tracke deinen Lifestyle für optimale Ergebnisse.", en: "Track your lifestyle for optimal results." },
  "lifestyle.sleep": { de: "Schlaf", en: "Sleep" },
  "lifestyle.water": { de: "Wasser", en: "Water" },
  "lifestyle.exercise": { de: "Training", en: "Exercise" },
  "lifestyle.nutrition": { de: "Ernährung", en: "Nutrition" },
  "lifestyle.supplements": { de: "Supplements", en: "Supplements" },
  "lifestyle.skincare": { de: "Skincare", en: "Skincare" },
  "lifestyle.fasting": { de: "Fasten", en: "Fasting" },
  "lifestyle.mood": { de: "Stimmung", en: "Mood" },
  "lifestyle.lowSleep": { de: "geschlafen – gönn dir mehr Ruhe!", en: "of sleep – get more rest!" },
  "lifestyle.lowWater": { de: "getrunken – trink mehr Wasser!", en: "drunk – drink more water!" },
  "lifestyle.goodDay": { de: "Perfekter Tag! Weiter so! 🌟", en: "Perfect day! Keep it up! 🌟" },
  "lifestyle.goals": { de: "Ziele", en: "Goals" },
  "lifestyle.challenges": { de: "Challenges", en: "Challenges" },

  // Affiliate Page
  "affiliate.title": { de: "Affiliate Programm", en: "Affiliate Program" },
  "affiliate.yourLink": { de: "Dein Affiliate-Link", en: "Your Affiliate Link" },
  "affiliate.stats": { de: "Statistiken", en: "Statistics" },
  "affiliate.earnings": { de: "Verdienst", en: "Earnings" },
  "affiliate.referrals": { de: "Empfehlungen", en: "Referrals" },
  "affiliate.payout": { de: "Auszahlung", en: "Payout" },
  "affiliate.payoutSettings": { de: "Auszahlungseinstellungen", en: "Payout Settings" },
  "affiliate.requestPayout": { de: "Auszahlung anfordern", en: "Request Payout" },
  "affiliate.payoutHistory": { de: "Auszahlungsverlauf", en: "Payout History" },
  "affiliate.commission": { de: "Provision", en: "Commission" },
  "affiliate.totalEarnings": { de: "Gesamtverdienst", en: "Total Earnings" },
  "affiliate.pendingEarnings": { de: "Ausstehend", en: "Pending" },
  "affiliate.paidEarnings": { de: "Ausgezahlt", en: "Paid" },
  "affiliate.copyLink": { de: "Link kopieren", en: "Copy link" },
  "affiliate.shareLink": { de: "Link teilen", en: "Share link" },

  // Pricing  
  "pricing.backToHome": { de: "Zurück zur Startseite", en: "Back to Home" },

  // Mobile Dashboard
  "mobile.analysis": { de: "Analyse", en: "Analysis" },
  "mobile.plan": { de: "Plan", en: "Plan" },
  "mobile.lifestyle": { de: "Lifestyle", en: "Lifestyle" },
  "mobile.friends": { de: "Freunde", en: "Friends" },

  // Index/Landing
  "index.loading": { de: "Lade...", en: "Loading..." },
  "index.redirecting": { de: "Weiterleitung...", en: "Redirecting..." },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      return (localStorage.getItem("app-language") as Language) || "de";
    } catch {
      return "de";
    }
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("app-language", lang);
    } catch {}
  }, []);

  const t = useCallback((key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] || entry.de || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}